using Ferrite.Core.Util;

namespace Ferrite.Core.Minecraft;

/// <summary>
/// The <c>eula.txt</c> Minecraft reads before it will run a server. The launcher writes it only when
/// the user has explicitly accepted the agreement for that instance: accepting a licence is a
/// decision the user makes, so it is never written silently.
/// </summary>
public static class EulaFile
{
    public const string FileName = "eula.txt";

    public static string Path(string gameDirectory) => System.IO.Path.Combine(gameDirectory, FileName);

    /// <summary>True when the file exists and records acceptance.</summary>
    public static bool IsAccepted(string gameDirectory)
    {
        var path = Path(gameDirectory);
        if (!File.Exists(path))
        {
            return false;
        }

        try
        {
            foreach (var line in File.ReadLines(path))
            {
                var trimmed = line.Trim();
                if (trimmed.StartsWith('#') || trimmed.Length == 0)
                {
                    continue;
                }

                var separator = trimmed.IndexOf('=');
                if (separator <= 0)
                {
                    continue;
                }

                var key = trimmed[..separator].Trim();
                var value = trimmed[(separator + 1)..].Trim();
                if (key.Equals("eula", StringComparison.OrdinalIgnoreCase))
                {
                    return value.Equals("true", StringComparison.OrdinalIgnoreCase);
                }
            }
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            return false;
        }

        return false;
    }

    /// <summary>
    /// Writes or removes the acceptance for an instance, matching the instance's stored setting. The
    /// comment line is Minecraft's own convention and keeps the file self-explanatory.
    /// </summary>
    public static bool Apply(string gameDirectory, bool accepted)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(gameDirectory);
        var path = Path(gameDirectory);

        if (!accepted)
        {
            // Only undo an acceptance this launcher wrote. A file the user created by hand is theirs.
            if (File.Exists(path) && WasWrittenByLauncher(path) && IsAccepted(gameDirectory))
            {
                AtomicFile.WriteAllText(path, "eula=false" + Environment.NewLine);
            }

            return false;
        }

        Directory.CreateDirectory(gameDirectory);
        AtomicFile.WriteAllText(
            path,
            "# Generated by Ferrite because the user accepted Minecraft's EULA for this instance."
            + Environment.NewLine
            + "eula=true"
            + Environment.NewLine);
        return true;
    }

    private const string LauncherMarker = "# Generated by Ferrite";

    private static bool WasWrittenByLauncher(string path)
    {
        try
        {
            using var reader = new StreamReader(path);
            while (reader.ReadLine() is { } line)
            {
                var trimmed = line.TrimStart();
                if (trimmed.Length == 0)
                {
                    continue;
                }

                return trimmed.StartsWith(LauncherMarker, StringComparison.Ordinal);
            }
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            return false;
        }

        return false;
    }
}
