using Ferrite.Core.Minecraft;

namespace Ferrite.Core.Tests;

/// <summary>
/// <c>eula.txt</c> handling. The row claiming this existed had no implementation behind it, so these
/// cover the file's contents and, importantly, what the launcher refuses to touch.
/// </summary>
public sealed class EulaFileTests : IDisposable
{
    private readonly string _gameDirectory;

    public EulaFileTests()
    {
        _gameDirectory = Path.Combine(Path.GetTempPath(), "ferrite-eula-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_gameDirectory);
    }

    public void Dispose()
    {
        try
        {
            Directory.Delete(_gameDirectory, recursive: true);
        }
        catch (IOException)
        {
        }
    }

    [Fact]
    public void A_missing_file_is_not_an_acceptance()
    {
        Assert.False(EulaFile.IsAccepted(_gameDirectory));
        Assert.False(EulaFile.IsAccepted(Path.Combine(_gameDirectory, "nowhere")));
    }

    [Theory]
    [InlineData("eula=true", true)]
    [InlineData("eula=TRUE", true)]
    [InlineData("eula = true", true)]
    [InlineData("eula=false", false)]
    [InlineData("# eula=true", false)]
    [InlineData("# a comment\neula=false\n", false)]
    [InlineData("something=else", false)]
    [InlineData("", false)]
    public void Acceptance_is_read_from_the_file(string contents, bool expected)
    {
        File.WriteAllText(EulaFile.Path(_gameDirectory), contents);

        Assert.Equal(expected, EulaFile.IsAccepted(_gameDirectory));
    }

    [Fact]
    public void Accepting_writes_the_file_the_game_reads()
    {
        Assert.True(EulaFile.Apply(_gameDirectory, accepted: true));

        var text = File.ReadAllText(EulaFile.Path(_gameDirectory));
        Assert.Contains("eula=true", text, StringComparison.Ordinal);
        Assert.Contains("# Generated by Ferrite", text, StringComparison.Ordinal);
        Assert.True(EulaFile.IsAccepted(_gameDirectory));
    }

    [Fact]
    public void Withdrawing_acceptance_undoes_what_the_launcher_wrote()
    {
        EulaFile.Apply(_gameDirectory, accepted: true);

        EulaFile.Apply(_gameDirectory, accepted: false);

        Assert.False(EulaFile.IsAccepted(_gameDirectory));
        Assert.Contains("eula=false", File.ReadAllText(EulaFile.Path(_gameDirectory)), StringComparison.Ordinal);
    }

    /// <summary>
    /// A file the user wrote by hand is theirs. Turning the launcher's toggle off must not rewrite an
    /// agreement someone else recorded.
    /// </summary>
    [Fact]
    public void A_file_the_user_wrote_is_left_alone()
    {
        File.WriteAllText(EulaFile.Path(_gameDirectory), "# I accepted this myself\neula=true\n");

        EulaFile.Apply(_gameDirectory, accepted: false);

        Assert.True(EulaFile.IsAccepted(_gameDirectory));
        Assert.Contains("I accepted this myself", File.ReadAllText(EulaFile.Path(_gameDirectory)), StringComparison.Ordinal);
    }

    [Fact]
    public void Accepting_creates_a_game_directory_that_does_not_exist_yet()
    {
        var missing = Path.Combine(_gameDirectory, "fresh-instance", "minecraft");

        Assert.True(EulaFile.Apply(missing, accepted: true));

        Assert.True(File.Exists(EulaFile.Path(missing)));
    }
}
