namespace Ferrite.App.Localization;

/// <summary>English interface text. This table is also the fallback for any missing key.</summary>
internal static class StringsEn
{
    internal static IReadOnlyDictionary<string, string> Table { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["L.App.Name"] = "Ferrite",
            ["L.App.Tagline"] = "Minecraft launcher",
            ["L.Nav.Library"] = "Library",
            ["L.Nav.Browse"] = "Browse",
            ["L.Nav.Java"] = "Java",
            ["L.Nav.Accounts"] = "Accounts",
            ["L.Nav.Settings"] = "Settings",
            ["L.Shell.Account"] = "ACCOUNT",
            ["L.Shell.NoAccount"] = "No account",
            ["L.Shell.QuickActions"] = "Quick actions",
            ["L.Shell.QuickActionsPlaceholder"] = "Type a command or an instance name",
            ["L.Quick.GoTo"] = "Go to {0}",
            ["L.Quick.OpenInstance"] = "Open {0}",
            ["L.Quick.LaunchInstance"] = "Launch {0}",
            ["L.Quick.NoMatches"] = "Nothing matches that.",
            ["L.Common.Ready"] = "Ready",
            ["L.Common.Dismiss"] = "Dismiss",
            ["L.Common.Cancel"] = "Cancel",
            ["L.Common.Refresh"] = "Refresh",
            ["L.Common.Folder"] = "Folder",
            ["L.Common.OpenFolder"] = "Open folder",
            ["L.Common.Add"] = "Add",
            ["L.Common.Remove"] = "Remove",
            ["L.Common.Delete"] = "Delete",
            ["L.Common.OpenFile"] = "Open",
            ["L.Common.Repair"] = "Repair",
            ["L.Common.Save"] = "Save",
            ["L.Shell.Error"] = "Something went wrong",
            ["L.Activity.Resolving"] = "Resolving metadata...",
            ["L.Activity.Planning"] = "Planning {0}...",
            ["L.Activity.Downloading"] = "Downloading...",
            ["L.Activity.DownloadingItem"] = "Downloading {0} ({1})",
            ["L.Activity.ExtractingNatives"] = "Extracting natives ({0})",
            ["L.Activity.Finishing"] = "Finishing...",

            ["L.Library.SearchInstances"] = "Search instances",
            ["L.Library.SortRecent"] = "Recently played",
            ["L.Library.SortName"] = "Sort by name",
            ["L.Library.SortVersion"] = "Sort by Minecraft version",
            ["L.Library.SortSize"] = "Sort by size on disk",
            ["L.Library.ImportModpack"] = "Import modpack",
            ["L.Library.NewInstance"] = "New instance",
            ["L.Library.Empty"] =
                "No instances yet. Create one to install Minecraft, optionally with a mod loader.",
            ["L.Library.Play"] = "Play",
            ["L.Library.Stop"] = "Stop",
            ["L.Library.Manage"] = "Manage",
            ["L.Library.Rename"] = "Rename",
            ["L.Library.Clone"] = "Clone",
            ["L.Library.RenameTitle"] = "Rename instance",
            ["L.Library.CloneTitle"] = "Clone instance",
            ["L.Library.CloneHint"] =
                "The clone copies this instance's mods, configs, and settings into an independent instance.",
            ["L.Library.Move"] = "Move",
            ["L.Library.GroupTitle"] = "Move to folder",
            ["L.Library.GroupHint"] =
                "Folders only organise the library. Type a name to file this instance, or clear the box "
                + "to take it out of its folder.",
            ["L.Library.GroupAll"] = "All folders",
            ["L.Library.MoveToFolder"] = "Move to folder",
            ["L.Library.FolderChip"] = "Folder: {0}",
            ["L.Library.CreateTitle"] = "New instance",
            ["L.Library.FieldName"] = "NAME",
            ["L.Library.FieldMinecraftVersion"] = "MINECRAFT VERSION",
            ["L.Library.ShowSnapshots"] = "Show snapshots",
            ["L.Library.FieldLoader"] = "MOD LOADER",
            ["L.Library.FieldLoaderVersion"] = "LOADER VERSION",
            ["L.Library.FieldGroup"] = "FOLDER",
            ["L.Library.CreateAndInstall"] = "Create and install",

            ["L.Browse.Search"] = "Search",
            ["L.Browse.RefreshInstances"] = "Refresh instances",
            ["L.Browse.FieldMinecraftVersion"] = "Minecraft version",
            ["L.Browse.FieldLoader"] = "Loader",
            ["L.Browse.FieldCategory"] = "Category",
            ["L.Browse.FieldProvider"] = "Source",
            ["L.Browse.FieldProjectType"] = "Content type",
            ["L.Browse.FieldSort"] = "Order",
            ["L.Browse.AnyCategory"] = "Any category",
            ["L.Browse.AnyVersion"] = "Any version",
            ["L.Browse.AnyLoader"] = "Any loader",
            ["L.Browse.About"] = "ABOUT THIS PROJECT",
            ["L.Browse.Changelog"] = "CHANGELOG",
            ["L.Browse.NoChangelog"] = "The provider published no changelog for this version.",
            ["L.Browse.Gallery"] = "GALLERY",
            ["L.Browse.BodyTruncated"] = "… description truncated; open the project page for the rest.",
            ["L.Browse.Empty"] =
                "Search a provider for mods, modpacks, resource packs, and shaders. Results are filtered "
                + "to the selected instance's Minecraft version and loader.",
            ["L.Browse.InstallInto"] = "INSTALL INTO",
            ["L.Browse.Saved"] = "Saved",
            ["L.Browse.SearchResults"] = "Search results",
            ["L.Browse.Save"] = "Save",
            ["L.Browse.Unsave"] = "Remove from saved",
            ["L.Browse.SavedProject"] = "Saved {0}",
            ["L.Browse.UnsavedProject"] = "Removed {0} from saved",
            ["L.Browse.SavedSummary"] = "{0} saved project(s) for this provider",
            ["L.Browse.NoSaved"] =
                "Nothing is saved for this provider yet. Search, then use Save on a project.",
            ["L.Browse.FieldVersion"] = "VERSION",
            ["L.Browse.IncludeOptional"] = "Include optional dependencies",
            ["L.Browse.OpenProjectPage"] = "Open project page",
            ["L.Browse.Install"] = "Install",
            ["L.Browse.SelectProject"] = "Select a project to see its versions and install it.",
            ["L.Browse.SearchPlaceholder"] = "Search {0}",
            ["L.Browse.Results"] = "{0:N0} results",
            ["L.Browse.Installed"] = "Installed {0} file(s) into {1}",
            ["L.Browse.Warnings"] = "{0} warning(s)",

            ["L.Accounts.Hint"] =
                "Sign-in uses Microsoft's device-code flow. Ferrite never sees or stores your password.",
            ["L.Accounts.ClientIdPlaceholder"] = "Microsoft client id (Azure public client)",
            ["L.Accounts.SaveClientId"] = "Save client id",
            ["L.Accounts.SignIn"] = "Sign in",
            ["L.Accounts.FieldCode"] = "CODE",
            ["L.Accounts.OpenSignInPage"] = "Open sign-in page",
            ["L.Accounts.Use"] = "Use",
            ["L.Accounts.SignOut"] = "Sign out",
            ["L.Accounts.Empty"] = "No accounts yet. Add a Microsoft client id, then sign in.",
            ["L.Accounts.Degraded"] =
                "Credential protection is degraded on this platform; tokens are stored with user-only "
                + "file permissions.",

            ["L.Java.Hint"] =
                "Ferrite probes each runtime by running it, so only working installations are listed.",
            ["L.Java.Rescan"] = "Rescan",
            ["L.Java.UseAsDefault"] = "Use as default",
            ["L.Java.DownloadHint"] = "DOWNLOAD A RUNTIME FROM MOJANG",
            ["L.Java.ListBuilds"] = "List builds",
            ["L.Java.Download"] = "Download",

            ["L.Settings.Appearance"] = "Appearance",
            ["L.Settings.FieldTheme"] = "THEME",
            ["L.Settings.FieldLanguage"] = "LANGUAGE",
            ["L.Settings.ShowSnapshots"] = "Show snapshots in the version list",
            ["L.Settings.Network"] = "Network",
            ["L.Settings.FieldConcurrentDownloads"] = "CONCURRENT DOWNLOADS",
            ["L.Settings.FieldProxy"] = "HTTP PROXY",
            ["L.Settings.FieldMirrors"] = "MIRRORS (one host=url per line)",
            ["L.Settings.MirrorsPlaceholder"] = "launchermeta.mojang.com=https://mirror.example/mojang",
            ["L.Settings.MirrorsHint"] =
                "Redirects artifact and metadata requests for a host to a mirror you trust. Path and "
                + "query are preserved, so the mirror must use the same layout.",
            ["L.Settings.Accounts"] = "Accounts",
            ["L.Settings.FieldClientId"] = "MICROSOFT CLIENT ID",
            ["L.Settings.ClientIdHint"] =
                "Required for Microsoft sign-in. See docs/HUMAN_ACTION_REQUIRED.md for the exact steps.",
            ["L.Settings.Providers"] = "Content providers",
            ["L.Settings.FieldCurseForgeKey"] = "CURSEFORGE API KEY",
            ["L.Settings.CurseForgeKeyPlaceholder"] = "Paste a key to store or replace the current one",
            ["L.Settings.RemoveKey"] = "Remove key",
            ["L.Settings.CurseForgeHint"] =
                "CurseForge browsing, mod installation, and modpack imports need a key issued to you by "
                + "CurseForge. The key is stored outside the settings file. See docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Settings.Storage"] = "Storage",
            ["L.Settings.FieldDataRoot"] = "DATA ROOT",
            ["L.Settings.DataRootHint"] =
                "Moving the folder copies the launcher's data and takes effect on the next start. The "
                + "FERRITE_HOME environment variable still overrides this.",
            ["L.Settings.MoveDataFolder"] = "Move data folder",
            ["L.Settings.UseDefaultDataFolder"] = "Use default location",
            ["L.Settings.DataFolderMoved"] =
                "Copied {0} file(s) ({1}) to {2}. Restart Ferrite to use the new folder.",
            ["L.Settings.DataFolderInvalid"] = "That folder cannot be used: {0}",
            ["L.Settings.DataFolderReverted"] =
                "The launcher will use its default data location on the next start.",
            ["L.Settings.DataFolderAlreadyDefault"] =
                "The launcher is already using its default data location.",
            ["L.Settings.FieldCacheSize"] = "LIBRARY AND CACHE SIZE",
            ["L.Settings.OpenDataFolder"] = "Open data folder",
            ["L.Settings.OpenLogs"] = "Open logs",
            ["L.Settings.RefreshSize"] = "Refresh size",
            ["L.Settings.ClearMetadataCache"] = "Clear metadata cache",
            ["L.Settings.Updates"] = "Launcher updates",
            ["L.Settings.FieldUpdateFeed"] = "UPDATE FEED URL",
            ["L.Settings.CheckOnStartup"] = "Check for updates when Ferrite starts",
            ["L.Settings.CheckForUpdates"] = "Check for updates",
            ["L.Settings.DownloadAndVerify"] = "Download and verify",
            ["L.Settings.OpenStaging"] = "Open staging folder",
            ["L.Settings.HandoffHint"] = "CLOSE FERRITE, THEN RUN",
            ["L.Settings.FeedHint"] =
                "A feed must publish a manifest.json signed by the key built into this copy of Ferrite. "
                + "Ferrite never replaces its own running files; the staged build is applied by the script "
                + "above, which waits for Ferrite to close. See docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Settings.Diagnostics"] = "Diagnostics",
            ["L.Settings.FieldRecentOperations"] = "RECENT OPERATIONS",
            ["L.Settings.NoOperations"] = "No operations recorded yet.",
            ["L.Settings.FieldBundleNotes"] = "SUPPORT BUNDLE NOTES",
            ["L.Settings.BundleNotesPlaceholder"] = "What were you doing when it went wrong?",
            ["L.Settings.ExportDiagnostics"] = "Export diagnostics bundle",
            ["L.Settings.RefreshList"] = "Refresh list",
            ["L.Settings.BundleHint"] =
                "The bundle contains launcher logs, this operation list, and the newest crash report's "
                + "analysis. Credentials are redacted before anything is written.",
            ["L.Settings.SaveSettings"] = "Save settings",
            ["L.Settings.Saved"] = "Settings saved",
            ["L.Settings.KeyRemoved"] = "CurseForge API key removed",
            ["L.Settings.NoFeed"] = "No update feed is configured.",
            ["L.Settings.CheckFirst"] = "Check for updates first.",
            ["L.Settings.UpToDate"] = "Ferrite {0} is the newest release on this feed.",
            ["L.Settings.NoPackage"] =
                "Ferrite {0} is available, but the feed publishes no build for this machine.",
            ["L.Settings.UpdateAvailable"] = "Ferrite {0} is available ({1}).",
            ["L.Settings.Staged"] =
                "Ferrite {0} is staged and verified ({1}). Close Ferrite, then run the command below.",
            ["L.Settings.CacheCleared"] =
                "Metadata cache cleared; it will be fetched again when needed.",

            ["L.Instance.Back"] = "Back",
            ["L.Instance.Verify"] = "Verify",
            ["L.Instance.ExportPack"] = "Export pack",
            ["L.Instance.UpdateFromPack"] = "Apply pack over this instance",
            ["L.Instance.UpdatedFromPack"] =
                "Applied the pack: {0} file(s) downloaded, {1} override(s).",
            ["L.Instance.TabSettings"] = "Settings",
            ["L.Instance.TabMods"] = "Mods",
            ["L.Instance.TabContent"] = "Content",
            ["L.Instance.TabWorlds"] = "Worlds",
            ["L.Instance.TabServers"] = "Servers",
            ["L.Instance.TabFiles"] = "Files",
            ["L.Instance.TabLogs"] = "Logs",
            ["L.Instance.FieldJavaRuntime"] = "JAVA RUNTIME",
            ["L.Instance.FieldMaxMemory"] = "MAX MEMORY (MB)",
            ["L.Instance.FieldMinMemory"] = "MIN MEMORY (MB)",
            ["L.Instance.FieldWindowSize"] = "WINDOW SIZE",
            ["L.Instance.FieldWindowWidth"] = "Window width",
            ["L.Instance.FieldWindowHeight"] = "Window height",
            ["L.Common.SelectItem"] = "Select this item",
            ["L.Instance.WindowSizeHint"] = "width x height, blank for the default",
            ["L.Instance.FieldDefaultServer"] = "DEFAULT SERVER (used when joining from the library)",
            ["L.Instance.FieldGroup"] = "FOLDER",
            ["L.Instance.FieldGroupHint"] =
                "Folders only organise the library; they never change the instance's files.",
            ["L.Instance.FieldThemeAccent"] = "ACCENT COLOUR (hex, optional)",
            ["L.Instance.ThemeHint"] =
                "The accent tints this instance's banner, and the background image is copied into the "
                + "instance so it cannot break when you move the original.",
            ["L.Instance.ThemeAccentInvalid"] =
                "That is not a colour. Use a hex value such as #D08A3E, or leave it empty.",
            ["L.Instance.ChooseThemeBackground"] = "Background image",
            ["L.Instance.ClearThemeBackground"] = "Clear background",
            ["L.Instance.ThemeBackgroundSet"] = "Background saved for this instance",
            ["L.Instance.ThemeBackgroundCleared"] = "Background cleared",
            ["L.Instance.DemoMode"] = "Launch in demo mode",
            ["L.Instance.AcceptEula"] = "Accept Minecraft's EULA for this instance (writes eula.txt)",
            ["L.Instance.AcceptEulaHint"] =
                "Minecraft requires this before it will run a server. Accepting the agreement is your "
                + "decision, so Ferrite never sets it without you.",
            ["L.Instance.FieldJvmArguments"] = "EXTRA JVM ARGUMENTS (one per line)",
            ["L.Instance.FieldGameArguments"] = "EXTRA GAME ARGUMENTS (one per line)",
            ["L.Instance.DropModsHint"] = "Drop mod files here, or use Add mods.",
            ["L.Instance.Loader"] = "LOADER",
            ["L.Instance.LoaderVanilla"] = "Vanilla (no loader)",
            ["L.Instance.LoaderVersion"] = "MOD LOADER VERSION",
            ["L.Instance.LoaderStable"] = "stable",
            ["L.Instance.ApplyLoaderVersion"] = "Use this version",
            ["L.Instance.NoLoaderToChange"] =
                "This instance runs vanilla Minecraft, so there is no loader version to change.",
            ["L.Instance.NoLoaderBuilds"] = "No loader build is published for Minecraft {0}.",
            ["L.Instance.LoaderBuilds"] = "{0} loader build(s) available.",
            ["L.Instance.LoaderAlreadyCurrent"] = "Already running {0}.",
            ["L.Instance.LoaderSwitched"] = "This instance now runs {0} {1}.",
            ["L.Instance.InstallOptiFine"] = "Install OptiFine from a downloaded installer...",
            ["L.Instance.InstallLabyMod"] = "Install LabyMod",
            ["L.Instance.LabyModHint"] =
                "LabyMod publishes its own build per Minecraft version, which Ferrite installs and runs.",
            ["L.Instance.LabyModInstalling"] = "Installing LabyMod...",
            ["L.Instance.LabyModInstalled"] = "Installed LabyMod {0} as {1}",
            ["L.Instance.OptiFineHint"] =
                "OptiFine publishes no API, so its installer runs on your machine and you click Install "
                + "in its own window. Ferrite starts it with the right Java, then adopts what it "
                + "produced into this launcher's own store.",
            ["L.Instance.NotAnOptiFineInstaller"] =
                "{0} is not an OptiFine installer. Download OptiFine_x.y.z_HD_U_x.jar from optifine.net.",
            ["L.Instance.OptiFineVersionMismatch"] =
                "That installer is for Minecraft {0}, but this instance runs {1}.",
            ["L.Instance.OptiFineNeedsJava"] =
                "Installing OptiFine for this version needs Java {0}, which is not installed.",
            ["L.Instance.OptiFineRunning"] = "Waiting for the OptiFine installer ({0})",
            ["L.Instance.OptiFineWaitingForInstaller"] =
                "Complete the OptiFine installer window; Ferrite adopts the result when it closes.",
            ["L.Instance.OptiFineInstallerFailed"] = "The OptiFine installer exited with code {0}.",
            ["L.Instance.OptiFineInstalled"] = "Installed {0}; this instance now launches with OptiFine.",
            ["L.Instance.OptiFineInstalledWithWarnings"] =
                "Installed OptiFine with {0} warning(s); check the launcher log.",
            ["L.Instance.AddMods"] = "Add mods",
            ["L.Instance.Disable"] = "Disable",
            ["L.Instance.Enable"] = "Enable",
            ["L.Instance.NoMods"] = "No mods installed in this instance.",
            ["L.Instance.NoModMatches"] = "No installed mod matches the search.",
            ["L.Instance.ModSearchPlaceholder"] = "Search mods",
            ["L.Instance.ModLoaderAll"] = "All loaders",
            ["L.Instance.ModGroupAll"] = "All groups",
            ["L.Instance.ModGroups"] = "Groups",
            ["L.Instance.ModGroupHint"] =
                "A group is a name plus a rule: a mod joins it when its name or file name contains the "
                + "text you type. Groups are only a view over what is installed, so they never move a file.",
            ["L.Instance.ModGroupExisting"] = "EXISTING GROUP",
            ["L.Instance.ModGroupName"] = "NAME",
            ["L.Instance.ModGroupMatch"] = "NAME OR FILE NAME CONTAINS",
            ["L.Instance.FieldModGroup"] = "GROUP",
            ["L.Instance.ModGroupNeedsBoth"] = "A group needs both a name and a rule.",
            ["L.Instance.ModGroupSaved"] = "Group {0} saved",
            ["L.Instance.ModGroupRemoved"] = "Group {0} removed",
            ["L.Instance.TabAssistant"] = "Assistant",
            ["L.Instance.TabLocalServer"] = "Local server",
            ["L.Instance.TabMap"] = "Map",
            ["L.Instance.TabStructure"] = "Structure",
            ["L.Instance.StructureInWorlds"] = "STRUCTURES IN THIS INSTANCE",
            ["L.Instance.StructureLoad"] = "Preview",
            ["L.Instance.StructureChoose"] = "Choose a structure file",
            ["L.Instance.StructureMaterials"] = "MATERIALS",
            ["L.Instance.StructureReading"] = "Reading the structure...",
            ["L.Instance.StructureLoaded"] = "Previewing {0}",
            ["L.Instance.StructureNoneFound"] =
                "This instance has no structure files yet. Choose one, or generate some in game.",
            ["L.Instance.StructureSummary"] =
                "{0} x {1} x {2} blocks · {3} block(s) · {4} material(s)",
            ["L.Instance.StructureSameVersion"] =
                "Saved by this exact game version: it will load here.",
            ["L.Instance.StructureOlder"] =
                "Saved by an older game version: it should load, and the game will update it.",
            ["L.Instance.StructureNewer"] =
                "Saved by a newer game version: blocks this version does not know may be replaced.",
            ["L.Instance.StructureNoVersion"] =
                "The file declares no data version, so compatibility cannot be checked.",
            ["L.Instance.StructureNoGame"] =
                "This instance's client file was not found, so compatibility cannot be checked.",
            ["L.Instance.StructureUnknown"] = "Compatibility could not be determined.",
            ["L.Instance.MapWorld"] = "WORLD",
            ["L.Instance.MapCopyTo"] = "COPY CHUNKS INTO",
            ["L.Instance.MapRefresh"] = "Render the map",
            ["L.Instance.MapClearSelection"] = "Clear selection",
            ["L.Instance.MapDelete"] = "Delete selected chunks",
            ["L.Instance.MapCopy"] = "Copy selected chunks",
            ["L.Instance.MapSelection"] = "{0} chunk(s) selected",
            ["L.Instance.MapRendering"] = "Reading the world's chunks...",
            ["L.Instance.MapRendered"] = "Rendered {0} of {1} possible chunk(s).",
            ["L.Instance.MapEmpty"] = "This world has no chunks on disk yet.",
            ["L.Instance.MapNoWorlds"] = "This instance has no saved worlds.",
            ["L.Instance.MapNoSelection"] = "Select chunks on the map first.",
            ["L.Instance.MapCopyTarget"] = "Choose a different world to copy into.",
            ["L.Instance.MapDeleting"] = "Deleting the selected chunks...",
            ["L.Instance.MapDeleted"] = "Deleted {0} chunk(s); the region files were backed up first.",
            ["L.Instance.MapCopying"] = "Copying the selected chunks...",
            ["L.Instance.MapCopied"] = "Copied {0} chunk(s) into {1}.",
            ["L.Instance.ServerHint"] =
                "Runs Minecraft's own server for this instance's version, in a folder of its own. The "
                + "settings below are the ones the launcher owns; anything else you put in "
                + "server.properties is left alone.",
            ["L.Instance.ServerLevelName"] = "LEVEL NAME",
            ["L.Instance.ServerMotd"] = "MESSAGE OF THE DAY",
            ["L.Instance.ServerPort"] = "PORT",
            ["L.Instance.ServerMaxPlayers"] = "MAX PLAYERS",
            ["L.Instance.ServerMemory"] = "SERVER MEMORY",
            ["L.Instance.ServerOnlineMode"] = "Online mode",
            ["L.Instance.ServerAcceptEula"] = "Accept Minecraft's EULA for the server",
            ["L.Instance.ServerPrepare"] = "Prepare files",
            ["L.Instance.ServerStart"] = "Start server",
            ["L.Instance.ServerStop"] = "Stop server",
            ["L.Instance.ServerExport"] = "Export server",
            ["L.Instance.ServerPreparing"] = "Preparing the local server...",
            ["L.Instance.ServerPrepared"] = "Server files are ready in {0}",
            ["L.Instance.ServerRunning"] = "The server is running (pid {0}).",
            ["L.Instance.ServerExited"] = "The server exited with code {0}.",
            ["L.Instance.ServerStopped"] = "The server was asked to stop.",
            ["L.Instance.ServerNoJava"] = "No Java runtime is available for this version.",
            ["L.Instance.ServerExported"] = "Exported the server to {0}",
            ["L.Instance.RunAssistant"] = "Check this instance",
            ["L.Instance.AssistantHint"] =
                "Reads this instance's own logs, crash reports, mods, and files.",
            ["L.Instance.AssistantRunning"] = "Checking the instance...",
            ["L.Instance.AssistantFoundProblems"] = "The assistant found something to act on.",
            ["L.Instance.AssistantClean"] = "The assistant found nothing to act on.",
            ["L.Instance.SortName"] = "Sort by name",
            ["L.Instance.SortSize"] = "Sort by size",
            ["L.Instance.SortLoader"] = "Sort by loader",
            ["L.Instance.ModsShown"] = "Showing {0} of {1} mods",
            ["L.Instance.SelectAllMods"] = "Select all shown",
            ["L.Instance.ClearModSelection"] = "Clear selection",
            ["L.Instance.EnableSelected"] = "Enable selected",
            ["L.Instance.DisableSelected"] = "Disable selected",
            ["L.Instance.RemoveSelected"] = "Remove selected",
            ["L.Instance.ModsSelected"] = "{0} selected",
            ["L.Instance.EnabledMods"] = "Enabled {0} mod file(s).",
            ["L.Instance.DisabledMods"] = "Disabled {0} mod file(s).",
            ["L.Instance.RemovedMods"] =
                "Moved {0} mod file(s) out of the instance; they are kept in the launcher's backups folder.",
            ["L.Instance.NoModsRemoved"] = "No mod files could be moved out of the instance.",
            ["L.Instance.ModsFailed"] = "{0} mod file(s) could not be changed; each one says why.",
            ["L.Instance.CheckContentUpdates"] = "Check for updates",
            ["L.Instance.UpdateSelected"] = "Update selected",
            ["L.Instance.NoContentUpdates"] =
                "No updates found. Only content Ferrite installed can be checked; mods you added "
                + "yourself are left alone.",
            ["L.Instance.WorldsHint"] =
                "Backups and deleted worlds are written to the launcher's backups folder.",
            ["L.Instance.OpenSaves"] = "Open saves",
            ["L.Instance.Backup"] = "Backup",
            ["L.Instance.PlayWorld"] = "Play this world",
            ["L.Instance.Duplicate"] = "Duplicate",
            ["L.Instance.NoWorlds"] = "No saved worlds in this instance yet.",
            ["L.Instance.ServerNamePlaceholder"] = "Name (optional)",
            ["L.Instance.PingAll"] = "Ping all",
            ["L.Instance.SavedServers"] = "SAVED SERVERS",
            ["L.Instance.NoServers"] = "No saved servers. Add one to see its status here.",
            ["L.Instance.FindLanWorlds"] = "Find LAN worlds",
            ["L.Instance.ResourcePacks"] = "RESOURCE PACKS",
            ["L.Instance.ShaderPacks"] = "SHADER PACKS",
            ["L.Instance.Screenshots"] = "SCREENSHOTS",
            ["L.Instance.NoResourcePacks"] = "No resource packs.",
            ["L.Instance.NoShaderPacks"] = "No shader packs.",
            ["L.Instance.NoScreenshots"] = "No screenshots.",
            ["L.Instance.Datapacks"] = "DATAPACKS",
            ["L.Instance.NoDatapacks"] = "This world has no datapacks.",
            ["L.Instance.NoWorldsForDatapacks"] = "No saved worlds, so there are no datapacks to list.",
            ["L.Instance.CrashReports"] = "CRASH REPORTS",
            ["L.Instance.NoCrashReports"] = "No crash reports.",
            ["L.Instance.NoLogs"] = "No logs yet.",
            ["L.Instance.AddServerFirst"] = "Enter a server address first.",
            ["L.Instance.ServerAdded"] = "Server added",
            ["L.Instance.LanAdded"] = "Added to this instance's server list",
            ["L.Instance.LanSearching"] =
                "Searching the local network. Ask the other player to open their world to LAN.",
            ["L.Instance.LanNone"] = "No LAN worlds found yet.",
            ["L.Instance.LanStopped"] = "LAN search stopped.",
            ["L.Instance.LanUnavailable"] = "This machine cannot listen for LAN worlds: {0}",
            ["L.Instance.Verified"] = "Verified {0} files ({1})",
            ["L.Instance.CorruptFiles"] = "{0} file(s) missing or corrupt",
            ["L.Instance.Repaired"] = "Installation repaired",
            ["L.Instance.ProblemsRemain"] = "{0} problem(s) remain",
            ["L.Instance.SettingsSaved"] = "Settings saved",
            ["L.Instance.Exported"] = "Exported {0} file(s) to {1}",
            ["L.Instance.AddedMods"] = "Added {0} mod file(s)",
            ["L.Instance.NoModsAdded"] = "No mod files were added",

            ["L.Library.ModpackInstalled"] = "Installed {0}: {1}",
            ["L.Library.ModpackStatus"] = "{0}: {1} file(s), {2} override(s)",
            ["L.Library.ModpackUnsupported"] =
                "That archive is not a modpack: it has neither modrinth.index.json nor manifest.json.",
            ["L.Library.UnreadableFile"] = "That file could not be read.",
            ["L.Library.Installing"] = "Installing {0}...",
            ["L.Browse.NoCompatible"] =
                "No {0} version matches this instance's game version or loader.",
            ["L.Browse.ModpackNoDownload"] = "This modpack file cannot be downloaded automatically.",
            ["L.Browse.Downloading"] = "Downloading {0}...",
            ["L.Browse.CacheNote"] =
                "{0} is unreachable; showing results cached {1}.",
            ["L.Java.Found"] = "Found {0} runtime(s)",
            ["L.Java.AddPath"] = "Add a Java path",
            ["L.Java.PathRefused"] = "{0} did not answer as a Java runtime.",
            ["L.Java.PathAdded"] = "Added {0}.",
            ["L.Java.DefaultNow"] = "Default runtime is now {0}",
            ["L.Java.Provisioned"] = "Provisioned {0}",
            ["L.Accounts.NeedClientId"] =
                "Add a Microsoft client id first; see docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Accounts.Active"] = "Active account is {0}",
            ["L.Accounts.SignedOut"] = "Signed out",
            ["L.Instance.BackedUp"] = "Backed up to {0}",
            ["L.Instance.WorldMoved"] = "{0} was moved to {1}",
            ["L.Instance.WorldDuplicated"] = "Duplicated to {0}",
            ["L.Instance.SelectUpdate"] = "Select at least one update to apply.",
            ["L.Instance.Updated"] = "Updated {0} file(s)",
            ["L.Instance.Running"] = "{0} is running",
            ["L.Instance.Stopped"] = "{0} stopped",
            ["L.Library.InstanceRenamed"] = "Instance renamed",
            ["L.Library.InstanceCreated"] = "{0} created",
            ["L.Library.InstallingLoader"] = "Installing {0} {1}...",
            ["L.Library.InstanceReady"] = "{0} is ready",
            ["L.Library.MovedToBackups"] = "{0} was moved to backups",
            ["L.Library.Grouped"] = "{0} moved to {1}",
            ["L.Library.GroupCleared"] = "Instance taken out of its folder",
            ["L.Accounts.ClientIdCleared"] = "Client id cleared",
            ["L.Accounts.ClientIdSaved"] = "Client id saved",
            ["L.Java.NoBuilds"] = "Mojang publishes no {0} build for this platform",
            ["L.Java.Builds"] = "{0} published build(s) for {1}",
            ["L.Instance.ExitNormal"] = "Exited normally",
            ["L.Instance.ExitCode"] = "Exited with code {0}",
            ["L.Instance.RunningAs"] = "Running as process {0}",
            ["L.Instance.Healthy"] = "Installation is healthy",
            ["L.Instance.SkippedProvider"] = "{0} skipped: {1}",
            ["L.Instance.ProviderSummary"] = "{0}: {1} update(s), {2} up to date",
            ["L.Instance.NoTrackedContent"] =
                "No launcher-installed content is recorded for this instance yet.",
            ["L.Browse.ModpackDownloadFailed"] = "The modpack could not be downloaded.",
            ["L.Instance.LaunchFailed"] = "The instance could not be started.",
            ["L.Library.ChooseMinecraftVersion"] = "Choose a Minecraft version.",
            ["L.Library.ChooseLoaderVersion"] = "Choose a loader version.",
            ["L.Settings.KeyStoredDegraded"] =
                "Key stored with file permissions only (this platform has no OS-backed protection).",
            ["L.Settings.KeyStoredProtected"] =
                "Key stored and protected by the operating system.",
            ["L.Settings.NoKeyStored"] =
                "No key stored. CurseForge browsing and modpack installs stay disabled.",
        };
}
