namespace Ferrite.App.Localization;

/// <summary>English interface text. This table is also the fallback for any missing key.</summary>
internal static class StringsEn
{
    internal static IReadOnlyDictionary<string, string> Table { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["L.App.Name"] = "Ferrite",
            ["L.App.Tagline"] = "Minecraft launcher",
            ["L.Nav.Library"] = "Library",
            ["L.Nav.Browse"] = "Browse",
            ["L.Nav.Java"] = "Java",
            ["L.Nav.Accounts"] = "Accounts",
            ["L.Nav.Settings"] = "Settings",
            ["L.Shell.Account"] = "ACCOUNT",
            ["L.Shell.NoAccount"] = "No account",
            ["L.Common.Ready"] = "Ready",
            ["L.Common.Dismiss"] = "Dismiss",
            ["L.Common.Cancel"] = "Cancel",
            ["L.Common.Refresh"] = "Refresh",
            ["L.Common.Folder"] = "Folder",
            ["L.Common.OpenFolder"] = "Open folder",
            ["L.Common.Add"] = "Add",
            ["L.Common.Remove"] = "Remove",
            ["L.Common.Delete"] = "Delete",
            ["L.Common.Repair"] = "Repair",
            ["L.Common.Save"] = "Save",
            ["L.Shell.Error"] = "Something went wrong",
            ["L.Activity.Resolving"] = "Resolving metadata...",
            ["L.Activity.Planning"] = "Planning {0}...",
            ["L.Activity.Downloading"] = "Downloading...",
            ["L.Activity.DownloadingItem"] = "Downloading {0} ({1})",
            ["L.Activity.ExtractingNatives"] = "Extracting natives ({0})",
            ["L.Activity.Finishing"] = "Finishing...",

            ["L.Library.SearchInstances"] = "Search instances",
            ["L.Library.ImportModpack"] = "Import modpack",
            ["L.Library.NewInstance"] = "New instance",
            ["L.Library.Empty"] =
                "No instances yet. Create one to install Minecraft, optionally with a mod loader.",
            ["L.Library.Play"] = "Play",
            ["L.Library.Stop"] = "Stop",
            ["L.Library.Manage"] = "Manage",
            ["L.Library.Rename"] = "Rename",
            ["L.Library.Clone"] = "Clone",
            ["L.Library.RenameTitle"] = "Rename instance",
            ["L.Library.CloneTitle"] = "Clone instance",
            ["L.Library.CloneHint"] =
                "The clone copies this instance's mods, configs, and settings into an independent instance.",
            ["L.Library.CreateTitle"] = "New instance",
            ["L.Library.FieldName"] = "NAME",
            ["L.Library.FieldMinecraftVersion"] = "MINECRAFT VERSION",
            ["L.Library.ShowSnapshots"] = "Show snapshots",
            ["L.Library.FieldLoader"] = "MOD LOADER",
            ["L.Library.FieldLoaderVersion"] = "LOADER VERSION",
            ["L.Library.CreateAndInstall"] = "Create and install",

            ["L.Browse.Search"] = "Search",
            ["L.Browse.RefreshInstances"] = "Refresh instances",
            ["L.Browse.FieldMinecraftVersion"] = "Minecraft version",
            ["L.Browse.FieldLoader"] = "Loader",
            ["L.Browse.Empty"] =
                "Search a provider for mods, modpacks, resource packs, and shaders. Results are filtered "
                + "to the selected instance's Minecraft version and loader.",
            ["L.Browse.InstallInto"] = "INSTALL INTO",
            ["L.Browse.FieldVersion"] = "VERSION",
            ["L.Browse.IncludeOptional"] = "Include optional dependencies",
            ["L.Browse.OpenProjectPage"] = "Open project page",
            ["L.Browse.Install"] = "Install",
            ["L.Browse.SelectProject"] = "Select a project to see its versions and install it.",
            ["L.Browse.SearchPlaceholder"] = "Search {0}",
            ["L.Browse.Results"] = "{0:N0} results",
            ["L.Browse.Installed"] = "Installed {0} file(s) into {1}",
            ["L.Browse.Warnings"] = "{0} warning(s)",

            ["L.Accounts.Hint"] =
                "Sign-in uses Microsoft's device-code flow. Ferrite never sees or stores your password.",
            ["L.Accounts.ClientIdPlaceholder"] = "Microsoft client id (Azure public client)",
            ["L.Accounts.SaveClientId"] = "Save client id",
            ["L.Accounts.SignIn"] = "Sign in",
            ["L.Accounts.FieldCode"] = "CODE",
            ["L.Accounts.OpenSignInPage"] = "Open sign-in page",
            ["L.Accounts.Use"] = "Use",
            ["L.Accounts.SignOut"] = "Sign out",
            ["L.Accounts.Empty"] = "No accounts yet. Add a Microsoft client id, then sign in.",
            ["L.Accounts.Degraded"] =
                "Credential protection is degraded on this platform; tokens are stored with user-only "
                + "file permissions.",

            ["L.Java.Hint"] =
                "Ferrite probes each runtime by running it, so only working installations are listed.",
            ["L.Java.Rescan"] = "Rescan",
            ["L.Java.UseAsDefault"] = "Use as default",
            ["L.Java.DownloadHint"] = "DOWNLOAD A RUNTIME FROM MOJANG",
            ["L.Java.ListBuilds"] = "List builds",
            ["L.Java.Download"] = "Download",

            ["L.Settings.Appearance"] = "Appearance",
            ["L.Settings.FieldTheme"] = "THEME",
            ["L.Settings.FieldLanguage"] = "LANGUAGE",
            ["L.Settings.ShowSnapshots"] = "Show snapshots in the version list",
            ["L.Settings.Network"] = "Network",
            ["L.Settings.FieldConcurrentDownloads"] = "CONCURRENT DOWNLOADS",
            ["L.Settings.FieldProxy"] = "HTTP PROXY",
            ["L.Settings.Accounts"] = "Accounts",
            ["L.Settings.FieldClientId"] = "MICROSOFT CLIENT ID",
            ["L.Settings.ClientIdHint"] =
                "Required for Microsoft sign-in. See docs/HUMAN_ACTION_REQUIRED.md for the exact steps.",
            ["L.Settings.Providers"] = "Content providers",
            ["L.Settings.FieldCurseForgeKey"] = "CURSEFORGE API KEY",
            ["L.Settings.CurseForgeKeyPlaceholder"] = "Paste a key to store or replace the current one",
            ["L.Settings.RemoveKey"] = "Remove key",
            ["L.Settings.CurseForgeHint"] =
                "CurseForge browsing, mod installation, and modpack imports need a key issued to you by "
                + "CurseForge. The key is stored outside the settings file. See docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Settings.Storage"] = "Storage",
            ["L.Settings.FieldDataRoot"] = "DATA ROOT",
            ["L.Settings.DataRootHint"] =
                "Set the FERRITE_HOME environment variable to move the data root before launching.",
            ["L.Settings.FieldCacheSize"] = "LIBRARY AND CACHE SIZE",
            ["L.Settings.OpenDataFolder"] = "Open data folder",
            ["L.Settings.OpenLogs"] = "Open logs",
            ["L.Settings.RefreshSize"] = "Refresh size",
            ["L.Settings.ClearMetadataCache"] = "Clear metadata cache",
            ["L.Settings.Updates"] = "Launcher updates",
            ["L.Settings.FieldUpdateFeed"] = "UPDATE FEED URL",
            ["L.Settings.CheckOnStartup"] = "Check for updates when Ferrite starts",
            ["L.Settings.CheckForUpdates"] = "Check for updates",
            ["L.Settings.DownloadAndVerify"] = "Download and verify",
            ["L.Settings.OpenStaging"] = "Open staging folder",
            ["L.Settings.HandoffHint"] = "CLOSE FERRITE, THEN RUN",
            ["L.Settings.FeedHint"] =
                "A feed must publish a manifest.json signed by the key built into this copy of Ferrite. "
                + "Ferrite never replaces its own running files; the staged build is applied by the script "
                + "above, which waits for Ferrite to close. See docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Settings.Diagnostics"] = "Diagnostics",
            ["L.Settings.FieldRecentOperations"] = "RECENT OPERATIONS",
            ["L.Settings.NoOperations"] = "No operations recorded yet.",
            ["L.Settings.FieldBundleNotes"] = "SUPPORT BUNDLE NOTES",
            ["L.Settings.BundleNotesPlaceholder"] = "What were you doing when it went wrong?",
            ["L.Settings.ExportDiagnostics"] = "Export diagnostics bundle",
            ["L.Settings.RefreshList"] = "Refresh list",
            ["L.Settings.BundleHint"] =
                "The bundle contains launcher logs, this operation list, and the newest crash report's "
                + "analysis. Credentials are redacted before anything is written.",
            ["L.Settings.SaveSettings"] = "Save settings",
            ["L.Settings.Saved"] = "Settings saved",
            ["L.Settings.KeyRemoved"] = "CurseForge API key removed",
            ["L.Settings.NoFeed"] = "No update feed is configured.",
            ["L.Settings.CheckFirst"] = "Check for updates first.",
            ["L.Settings.UpToDate"] = "Ferrite {0} is the newest release on this feed.",
            ["L.Settings.NoPackage"] =
                "Ferrite {0} is available, but the feed publishes no build for this machine.",
            ["L.Settings.UpdateAvailable"] = "Ferrite {0} is available ({1}).",
            ["L.Settings.Staged"] =
                "Ferrite {0} is staged and verified ({1}). Close Ferrite, then run the command below.",
            ["L.Settings.CacheCleared"] =
                "Metadata cache cleared; it will be fetched again when needed.",

            ["L.Instance.Back"] = "Back",
            ["L.Instance.Verify"] = "Verify",
            ["L.Instance.ExportPack"] = "Export pack",
            ["L.Instance.TabSettings"] = "Settings",
            ["L.Instance.TabMods"] = "Mods",
            ["L.Instance.TabContent"] = "Content",
            ["L.Instance.TabWorlds"] = "Worlds",
            ["L.Instance.TabServers"] = "Servers",
            ["L.Instance.TabFiles"] = "Files",
            ["L.Instance.TabLogs"] = "Logs",
            ["L.Instance.FieldJavaRuntime"] = "JAVA RUNTIME",
            ["L.Instance.FieldMaxMemory"] = "MAX MEMORY (MB)",
            ["L.Instance.FieldMinMemory"] = "MIN MEMORY (MB)",
            ["L.Instance.FieldWindowSize"] = "WINDOW SIZE",
            ["L.Instance.WindowSizeHint"] = "width x height, blank for the default",
            ["L.Instance.FieldDefaultServer"] = "DEFAULT SERVER (used when joining from the library)",
            ["L.Instance.DemoMode"] = "Launch in demo mode",
            ["L.Instance.FieldJvmArguments"] = "EXTRA JVM ARGUMENTS (one per line)",
            ["L.Instance.FieldGameArguments"] = "EXTRA GAME ARGUMENTS (one per line)",
            ["L.Instance.DropModsHint"] = "Drop mod files here, or use Add mods.",
            ["L.Instance.AddMods"] = "Add mods",
            ["L.Instance.Disable"] = "Disable",
            ["L.Instance.Enable"] = "Enable",
            ["L.Instance.NoMods"] = "No mods installed in this instance.",
            ["L.Instance.CheckContentUpdates"] = "Check for updates",
            ["L.Instance.UpdateSelected"] = "Update selected",
            ["L.Instance.NoContentUpdates"] =
                "No updates found. Only content Ferrite installed can be checked; mods you added "
                + "yourself are left alone.",
            ["L.Instance.WorldsHint"] =
                "Backups and deleted worlds are written to the launcher's backups folder.",
            ["L.Instance.OpenSaves"] = "Open saves",
            ["L.Instance.Backup"] = "Backup",
            ["L.Instance.Duplicate"] = "Duplicate",
            ["L.Instance.NoWorlds"] = "No saved worlds in this instance yet.",
            ["L.Instance.ServerNamePlaceholder"] = "Name (optional)",
            ["L.Instance.PingAll"] = "Ping all",
            ["L.Instance.SavedServers"] = "SAVED SERVERS",
            ["L.Instance.NoServers"] = "No saved servers. Add one to see its status here.",
            ["L.Instance.FindLanWorlds"] = "Find LAN worlds",
            ["L.Instance.ResourcePacks"] = "RESOURCE PACKS",
            ["L.Instance.ShaderPacks"] = "SHADER PACKS",
            ["L.Instance.Screenshots"] = "SCREENSHOTS",
            ["L.Instance.NoResourcePacks"] = "No resource packs.",
            ["L.Instance.NoShaderPacks"] = "No shader packs.",
            ["L.Instance.NoScreenshots"] = "No screenshots.",
            ["L.Instance.CrashReports"] = "CRASH REPORTS",
            ["L.Instance.NoCrashReports"] = "No crash reports.",
            ["L.Instance.NoLogs"] = "No logs yet.",
            ["L.Instance.AddServerFirst"] = "Enter a server address first.",
            ["L.Instance.ServerAdded"] = "Server added",
            ["L.Instance.LanAdded"] = "Added to this instance's server list",
            ["L.Instance.LanSearching"] =
                "Searching the local network. Ask the other player to open their world to LAN.",
            ["L.Instance.LanNone"] = "No LAN worlds found yet.",
            ["L.Instance.LanStopped"] = "LAN search stopped.",
            ["L.Instance.LanUnavailable"] = "This machine cannot listen for LAN worlds: {0}",
            ["L.Instance.Verified"] = "Verified {0} files ({1})",
            ["L.Instance.CorruptFiles"] = "{0} file(s) missing or corrupt",
            ["L.Instance.Repaired"] = "Installation repaired",
            ["L.Instance.ProblemsRemain"] = "{0} problem(s) remain",
            ["L.Instance.SettingsSaved"] = "Settings saved",
            ["L.Instance.Exported"] = "Exported {0} file(s) to {1}",
            ["L.Instance.AddedMods"] = "Added {0} mod file(s)",
            ["L.Instance.NoModsAdded"] = "No mod files were added",

            ["L.Library.ModpackInstalled"] = "Installed {0}: {1}",
            ["L.Library.ModpackStatus"] = "{0}: {1} file(s), {2} override(s)",
            ["L.Library.ModpackUnsupported"] =
                "That archive is not a modpack: it has neither modrinth.index.json nor manifest.json.",
            ["L.Library.UnreadableFile"] = "That file could not be read.",
            ["L.Library.Installing"] = "Installing {0}...",
            ["L.Browse.NoCompatible"] =
                "No {0} version matches this instance's game version or loader.",
            ["L.Browse.ModpackNoDownload"] = "This modpack file cannot be downloaded automatically.",
            ["L.Browse.Downloading"] = "Downloading {0}...",
            ["L.Browse.CacheNote"] =
                "{0} is unreachable; showing results cached {1}.",
            ["L.Java.Found"] = "Found {0} runtime(s)",
            ["L.Java.DefaultNow"] = "Default runtime is now {0}",
            ["L.Java.Provisioned"] = "Provisioned {0}",
            ["L.Accounts.NeedClientId"] =
                "Add a Microsoft client id first; see docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Accounts.Active"] = "Active account is {0}",
            ["L.Accounts.SignedOut"] = "Signed out",
            ["L.Instance.BackedUp"] = "Backed up to {0}",
            ["L.Instance.WorldMoved"] = "{0} was moved to {1}",
            ["L.Instance.WorldDuplicated"] = "Duplicated to {0}",
            ["L.Instance.SelectUpdate"] = "Select at least one update to apply.",
            ["L.Instance.Updated"] = "Updated {0} file(s)",
            ["L.Instance.Running"] = "{0} is running",
            ["L.Instance.Stopped"] = "{0} stopped",
            ["L.Library.InstanceRenamed"] = "Instance renamed",
            ["L.Library.InstanceCreated"] = "{0} created",
            ["L.Library.InstallingLoader"] = "Installing {0} {1}...",
            ["L.Library.InstanceReady"] = "{0} is ready",
            ["L.Library.MovedToBackups"] = "{0} was moved to backups",
            ["L.Accounts.ClientIdCleared"] = "Client id cleared",
            ["L.Accounts.ClientIdSaved"] = "Client id saved",
            ["L.Java.NoBuilds"] = "Mojang publishes no {0} build for this platform",
            ["L.Java.Builds"] = "{0} published build(s) for {1}",
            ["L.Instance.ExitNormal"] = "Exited normally",
            ["L.Instance.ExitCode"] = "Exited with code {0}",
            ["L.Instance.RunningAs"] = "Running as process {0}",
            ["L.Instance.Healthy"] = "Installation is healthy",
            ["L.Instance.SkippedProvider"] = "{0} skipped: {1}",
            ["L.Instance.ProviderSummary"] = "{0}: {1} update(s), {2} up to date",
            ["L.Instance.NoTrackedContent"] =
                "No launcher-installed content is recorded for this instance yet.",
            ["L.Browse.ModpackDownloadFailed"] = "The modpack could not be downloaded.",
            ["L.Instance.LaunchFailed"] = "The instance could not be started.",
            ["L.Library.ChooseMinecraftVersion"] = "Choose a Minecraft version.",
            ["L.Library.ChooseLoaderVersion"] = "Choose a loader version.",
            ["L.Settings.KeyStoredDegraded"] =
                "Key stored with file permissions only (this platform has no OS-backed protection).",
            ["L.Settings.KeyStoredProtected"] =
                "Key stored and protected by the operating system.",
            ["L.Settings.NoKeyStored"] =
                "No key stored. CurseForge browsing and modpack installs stay disabled.",
        };
}
