namespace Ferrite.App.Localization;

/// <summary>Polish interface text. Keys match the English table exactly.</summary>
internal static class StringsPl
{
    internal static IReadOnlyDictionary<string, string> Table { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["L.App.Name"] = "Ferrite",
            ["L.App.Tagline"] = "Launcher Minecrafta",
            ["L.Nav.Library"] = "Biblioteka",
            ["L.Nav.Browse"] = "Przeglądaj",
            ["L.Nav.Java"] = "Java",
            ["L.Nav.Accounts"] = "Konta",
            ["L.Nav.Settings"] = "Ustawienia",
            ["L.Shell.Account"] = "KONTO",
            ["L.Shell.NoAccount"] = "Brak konta",
            ["L.Common.Ready"] = "Gotowe",
            ["L.Common.Dismiss"] = "Zamknij",
            ["L.Common.Cancel"] = "Anuluj",
            ["L.Common.Refresh"] = "Odśwież",
            ["L.Common.Folder"] = "Folder",
            ["L.Common.OpenFolder"] = "Otwórz folder",
            ["L.Common.Add"] = "Dodaj",
            ["L.Common.Remove"] = "Usuń",
            ["L.Common.Delete"] = "Usuń",
            ["L.Common.Repair"] = "Napraw",
            ["L.Common.Save"] = "Zapisz",
            ["L.Shell.Error"] = "Coś poszło nie tak",
            ["L.Activity.Resolving"] = "Odczytywanie metadanych...",
            ["L.Activity.Planning"] = "Planowanie: {0}...",
            ["L.Activity.Downloading"] = "Pobieranie...",
            ["L.Activity.DownloadingItem"] = "Pobieranie {0} ({1})",
            ["L.Activity.ExtractingNatives"] = "Wypakowywanie bibliotek natywnych ({0})",
            ["L.Activity.Finishing"] = "Kończenie...",

            ["L.Library.SearchInstances"] = "Szukaj instancji",
            ["L.Library.ImportModpack"] = "Importuj modpack",
            ["L.Library.NewInstance"] = "Nowa instancja",
            ["L.Library.Empty"] =
                "Nie ma jeszcze żadnej instancji. Utwórz ją, aby zainstalować Minecrafta, opcjonalnie z mod loaderem.",
            ["L.Library.Play"] = "Graj",
            ["L.Library.Stop"] = "Zatrzymaj",
            ["L.Library.Manage"] = "Zarządzaj",
            ["L.Library.Rename"] = "Zmień nazwę",
            ["L.Library.Clone"] = "Klonuj",
            ["L.Library.RenameTitle"] = "Zmień nazwę instancji",
            ["L.Library.CloneTitle"] = "Klonuj instancję",
            ["L.Library.CloneHint"] =
                "Klon kopiuje mody, konfiguracje i ustawienia tej instancji do niezależnej instancji.",
            ["L.Library.CreateTitle"] = "Nowa instancja",
            ["L.Library.FieldName"] = "NAZWA",
            ["L.Library.FieldMinecraftVersion"] = "WERSJA MINECRAFTA",
            ["L.Library.ShowSnapshots"] = "Pokaż snapshoty",
            ["L.Library.FieldLoader"] = "MOD LOADER",
            ["L.Library.FieldLoaderVersion"] = "WERSJA LOADERA",
            ["L.Library.CreateAndInstall"] = "Utwórz i zainstaluj",

            ["L.Browse.Search"] = "Szukaj",
            ["L.Browse.RefreshInstances"] = "Odśwież instancje",
            ["L.Browse.FieldMinecraftVersion"] = "Wersja Minecrafta",
            ["L.Browse.FieldLoader"] = "Loader",
            ["L.Browse.Empty"] =
                "Przeszukaj dostawcę treści w poszukiwaniu modów, modpacków, paczek zasobów i shaderów. "
                + "Wyniki są filtrowane według wersji Minecrafta i loadera wybranej instancji.",
            ["L.Browse.InstallInto"] = "ZAINSTALUJ W",
            ["L.Browse.FieldVersion"] = "WERSJA",
            ["L.Browse.IncludeOptional"] = "Uwzględnij opcjonalne zależności",
            ["L.Browse.OpenProjectPage"] = "Otwórz stronę projektu",
            ["L.Browse.Install"] = "Zainstaluj",
            ["L.Browse.SelectProject"] = "Wybierz projekt, aby zobaczyć jego wersje i zainstalować go.",
            ["L.Browse.SearchPlaceholder"] = "Szukaj w {0}",
            ["L.Browse.Results"] = "Wyniki: {0:N0}",
            ["L.Browse.Installed"] = "Zainstalowano {0} plik(ów) w instancji {1}",
            ["L.Browse.Warnings"] = "Ostrzeżenia: {0}",

            ["L.Accounts.Hint"] =
                "Logowanie korzysta z przepływu device code Microsoftu. Ferrite nigdy nie widzi ani nie zapisuje Twojego hasła.",
            ["L.Accounts.ClientIdPlaceholder"] = "Identyfikator klienta Microsoft (publiczny klient Azure)",
            ["L.Accounts.SaveClientId"] = "Zapisz identyfikator klienta",
            ["L.Accounts.SignIn"] = "Zaloguj się",
            ["L.Accounts.FieldCode"] = "KOD",
            ["L.Accounts.OpenSignInPage"] = "Otwórz stronę logowania",
            ["L.Accounts.Use"] = "Użyj",
            ["L.Accounts.SignOut"] = "Wyloguj się",
            ["L.Accounts.Empty"] =
                "Brak kont. Dodaj identyfikator klienta Microsoft, a następnie zaloguj się.",
            ["L.Accounts.Degraded"] =
                "Ochrona poświadczeń jest ograniczona na tej platformie; tokeny są przechowywane z uprawnieniami tylko dla użytkownika.",

            ["L.Java.Hint"] =
                "Ferrite sprawdza każde środowisko uruchamiając je, więc wymienione są tylko działające instalacje.",
            ["L.Java.Rescan"] = "Skanuj ponownie",
            ["L.Java.UseAsDefault"] = "Ustaw jako domyślne",
            ["L.Java.DownloadHint"] = "POBIERZ ŚRODOWISKO OD MOJANG",
            ["L.Java.ListBuilds"] = "Lista kompilacji",
            ["L.Java.Download"] = "Pobierz",

            ["L.Settings.Appearance"] = "Wygląd",
            ["L.Settings.FieldTheme"] = "MOTYW",
            ["L.Settings.FieldLanguage"] = "JĘZYK",
            ["L.Settings.ShowSnapshots"] = "Pokaż snapshoty na liście wersji",
            ["L.Settings.Network"] = "Sieć",
            ["L.Settings.FieldConcurrentDownloads"] = "RÓWNOLEGŁE POBIERANIA",
            ["L.Settings.FieldProxy"] = "PROXY HTTP",
            ["L.Settings.Accounts"] = "Konta",
            ["L.Settings.FieldClientId"] = "IDENTYFIKATOR KLIENTA MICROSOFT",
            ["L.Settings.ClientIdHint"] =
                "Wymagany do logowania przez Microsoft. Dokładne kroki opisuje docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Settings.Providers"] = "Dostawcy treści",
            ["L.Settings.FieldCurseForgeKey"] = "KLUCZ API CURSEFORGE",
            ["L.Settings.CurseForgeKeyPlaceholder"] = "Wklej klucz, aby zapisać lub zastąpić obecny",
            ["L.Settings.RemoveKey"] = "Usuń klucz",
            ["L.Settings.CurseForgeHint"] =
                "Przeglądanie CurseForge, instalowanie modów i import modpacków wymagają klucza wydanego "
                + "przez CurseForge. Klucz jest przechowywany poza plikiem ustawień. "
                + "Szczegóły w docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Settings.Storage"] = "Pamięć",
            ["L.Settings.FieldDataRoot"] = "KATALOG DANYCH",
            ["L.Settings.DataRootHint"] =
                "Ustaw zmienną środowiskową FERRITE_HOME, aby przenieść katalog danych przed uruchomieniem.",
            ["L.Settings.FieldCacheSize"] = "ROZMIAR BIBLIOTEKI I PAMIĘCI PODRĘCZNEJ",
            ["L.Settings.OpenDataFolder"] = "Otwórz katalog danych",
            ["L.Settings.OpenLogs"] = "Otwórz logi",
            ["L.Settings.RefreshSize"] = "Odśwież rozmiar",
            ["L.Settings.ClearMetadataCache"] = "Wyczyść pamięć podręczną metadanych",
            ["L.Settings.Updates"] = "Aktualizacje launchera",
            ["L.Settings.FieldUpdateFeed"] = "ADRES KANAŁU AKTUALIZACJI",
            ["L.Settings.CheckOnStartup"] = "Sprawdzaj aktualizacje przy starcie Ferrite",
            ["L.Settings.CheckForUpdates"] = "Sprawdź aktualizacje",
            ["L.Settings.DownloadAndVerify"] = "Pobierz i zweryfikuj",
            ["L.Settings.OpenStaging"] = "Otwórz katalog przygotowania",
            ["L.Settings.HandoffHint"] = "ZAMKNIJ FERRITE, NASTĘPNIE URUCHOM",
            ["L.Settings.FeedHint"] =
                "Kanał musi udostępniać manifest.json podpisany kluczem wbudowanym w tę kopię Ferrite. "
                + "Ferrite nigdy nie zastępuje własnych działających plików; przygotowana wersja jest "
                + "instalowana przez powyższy skrypt, który czeka na zamknięcie Ferrite. "
                + "Szczegóły w docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Settings.Diagnostics"] = "Diagnostyka",
            ["L.Settings.FieldRecentOperations"] = "OSTATNIE OPERACJE",
            ["L.Settings.NoOperations"] = "Nie zapisano jeszcze żadnych operacji.",
            ["L.Settings.FieldBundleNotes"] = "NOTATKI DO PAKIETU POMOCY",
            ["L.Settings.BundleNotesPlaceholder"] = "Co robiłeś, gdy wystąpił problem?",
            ["L.Settings.ExportDiagnostics"] = "Eksportuj pakiet diagnostyczny",
            ["L.Settings.RefreshList"] = "Odśwież listę",
            ["L.Settings.BundleHint"] =
                "Pakiet zawiera logi launchera, tę listę operacji oraz analizę najnowszego raportu awarii. "
                + "Poświadczenia są usuwane przed zapisem.",
            ["L.Settings.SaveSettings"] = "Zapisz ustawienia",
            ["L.Settings.Saved"] = "Ustawienia zapisane",
            ["L.Settings.KeyRemoved"] = "Klucz API CurseForge usunięty",
            ["L.Settings.NoFeed"] = "Nie skonfigurowano kanału aktualizacji.",
            ["L.Settings.CheckFirst"] = "Najpierw sprawdź aktualizacje.",
            ["L.Settings.UpToDate"] = "Ferrite {0} to najnowsze wydanie w tym kanale.",
            ["L.Settings.NoPackage"] =
                "Ferrite {0} jest dostępny, ale kanał nie udostępnia kompilacji dla tej maszyny.",
            ["L.Settings.UpdateAvailable"] = "Ferrite {0} jest dostępny ({1}).",
            ["L.Settings.Staged"] =
                "Ferrite {0} jest przygotowany i zweryfikowany ({1}). Zamknij Ferrite i uruchom poniższe polecenie.",
            ["L.Settings.CacheCleared"] =
                "Pamięć podręczna metadanych wyczyszczona; zostanie pobrana ponownie, gdy będzie potrzebna.",

            ["L.Instance.Back"] = "Wstecz",
            ["L.Instance.Verify"] = "Sprawdź",
            ["L.Instance.ExportPack"] = "Eksportuj paczkę",
            ["L.Instance.TabSettings"] = "Ustawienia",
            ["L.Instance.TabMods"] = "Mody",
            ["L.Instance.TabContent"] = "Treści",
            ["L.Instance.TabWorlds"] = "Światy",
            ["L.Instance.TabServers"] = "Serwery",
            ["L.Instance.TabFiles"] = "Pliki",
            ["L.Instance.TabLogs"] = "Logi",
            ["L.Instance.FieldJavaRuntime"] = "ŚRODOWISKO JAVA",
            ["L.Instance.FieldMaxMemory"] = "MAKS. PAMIĘĆ (MB)",
            ["L.Instance.FieldMinMemory"] = "MIN. PAMIĘĆ (MB)",
            ["L.Instance.FieldWindowSize"] = "ROZMIAR OKNA",
            ["L.Instance.WindowSizeHint"] = "szerokość x wysokość, puste dla domyślnego",
            ["L.Instance.FieldDefaultServer"] = "DOMYŚLNY SERWER (używany przy dołączaniu z biblioteki)",
            ["L.Instance.DemoMode"] = "Uruchom w trybie demo",
            ["L.Instance.FieldJvmArguments"] = "DODATKOWE ARGUMENTY JVM (jeden na linię)",
            ["L.Instance.FieldGameArguments"] = "DODATKOWE ARGUMENTY GRY (jeden na linię)",
            ["L.Instance.DropModsHint"] = "Przeciągnij pliki modów tutaj lub użyj opcji Dodaj mody.",
            ["L.Instance.AddMods"] = "Dodaj mody",
            ["L.Instance.Disable"] = "Wyłącz",
            ["L.Instance.Enable"] = "Włącz",
            ["L.Instance.NoMods"] = "W tej instancji nie ma zainstalowanych modów.",
            ["L.Instance.CheckContentUpdates"] = "Sprawdź aktualizacje",
            ["L.Instance.UpdateSelected"] = "Zaktualizuj wybrane",
            ["L.Instance.NoContentUpdates"] =
                "Nie znaleziono aktualizacji. Sprawdzane są tylko treści zainstalowane przez Ferrite; "
                + "modów dodanych samodzielnie launcher nie rusza.",
            ["L.Instance.WorldsHint"] =
                "Kopie zapasowe i usunięte światy trafiają do katalogu kopii launchera.",
            ["L.Instance.OpenSaves"] = "Otwórz zapisy",
            ["L.Instance.Backup"] = "Kopia zapasowa",
            ["L.Instance.Duplicate"] = "Duplikuj",
            ["L.Instance.NoWorlds"] = "Ta instancja nie ma jeszcze zapisanych światów.",
            ["L.Instance.ServerNamePlaceholder"] = "Nazwa (opcjonalna)",
            ["L.Instance.PingAll"] = "Pinguj wszystkie",
            ["L.Instance.SavedServers"] = "ZAPISANE SERWERY",
            ["L.Instance.NoServers"] = "Brak zapisanych serwerów. Dodaj jeden, aby zobaczyć jego status.",
            ["L.Instance.FindLanWorlds"] = "Szukaj światów w sieci lokalnej",
            ["L.Instance.ResourcePacks"] = "PACZKI ZASOBÓW",
            ["L.Instance.ShaderPacks"] = "PACZKI SHADERÓW",
            ["L.Instance.Screenshots"] = "ZDJĘCIA EKRANU",
            ["L.Instance.NoResourcePacks"] = "Brak paczek zasobów.",
            ["L.Instance.NoShaderPacks"] = "Brak paczek shaderów.",
            ["L.Instance.NoScreenshots"] = "Brak zdjęć ekranu.",
            ["L.Instance.CrashReports"] = "RAPORTY AWARII",
            ["L.Instance.NoCrashReports"] = "Brak raportów awarii.",
            ["L.Instance.NoLogs"] = "Brak logów.",
            ["L.Instance.AddServerFirst"] = "Najpierw podaj adres serwera.",
            ["L.Instance.ServerAdded"] = "Serwer dodany",
            ["L.Instance.LanAdded"] = "Dodano do listy serwerów tej instancji",
            ["L.Instance.LanSearching"] =
                "Przeszukiwanie sieci lokalnej. Poproś drugiego gracza o otwarcie świata w sieci LAN.",
            ["L.Instance.LanNone"] = "Nie znaleziono jeszcze światów w sieci LAN.",
            ["L.Instance.LanStopped"] = "Wyszukiwanie w sieci LAN zatrzymane.",
            ["L.Instance.LanUnavailable"] = "Ta maszyna nie może nasłuchiwać światów LAN: {0}",
            ["L.Instance.Verified"] = "Sprawdzono {0} plików ({1})",
            ["L.Instance.CorruptFiles"] = "Brakujące lub uszkodzone pliki: {0}",
            ["L.Instance.Repaired"] = "Instalacja naprawiona",
            ["L.Instance.ProblemsRemain"] = "Pozostało problemów: {0}",
            ["L.Instance.SettingsSaved"] = "Ustawienia zapisane",
            ["L.Instance.Exported"] = "Wyeksportowano {0} plik(ów) do {1}",
            ["L.Instance.AddedMods"] = "Dodano {0} plik(ów) modów",
            ["L.Instance.NoModsAdded"] = "Nie dodano żadnych plików modów",

            ["L.Library.ModpackInstalled"] = "Zainstalowano {0}: {1}",
            ["L.Library.ModpackStatus"] = "{0}: {1} plik(ów), {2} nadpisań",
            ["L.Library.ModpackUnsupported"] =
                "To archiwum nie jest modpackiem: nie zawiera ani modrinth.index.json, ani manifest.json.",
            ["L.Library.UnreadableFile"] = "Nie udało się odczytać tego pliku.",
            ["L.Library.Installing"] = "Instalowanie {0}...",
            ["L.Browse.NoCompatible"] =
                "Żadna wersja {0} nie pasuje do wersji gry ani loadera tej instancji.",
            ["L.Browse.ModpackNoDownload"] = "Tego pliku modpacka nie można pobrać automatycznie.",
            ["L.Browse.Downloading"] = "Pobieranie {0}...",
            ["L.Browse.CacheNote"] =
                "{0} jest nieosiągalny; wyświetlane są wyniki z pamięci podręcznej ({1}).",
            ["L.Java.Found"] = "Znalezione środowiska: {0}",
            ["L.Java.DefaultNow"] = "Domyślne środowisko to teraz {0}",
            ["L.Java.Provisioned"] = "Zainstalowano {0}",
            ["L.Accounts.NeedClientId"] =
                "Najpierw dodaj identyfikator klienta Microsoft; szczegóły w docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Accounts.Active"] = "Aktywne konto: {0}",
            ["L.Accounts.SignedOut"] = "Wylogowano",
            ["L.Instance.BackedUp"] = "Kopia zapasowa: {0}",
            ["L.Instance.WorldMoved"] = "Przeniesiono {0} do {1}",
            ["L.Instance.WorldDuplicated"] = "Zduplikowano do {0}",
            ["L.Instance.SelectUpdate"] = "Wybierz co najmniej jedną aktualizację do zastosowania.",
            ["L.Instance.Updated"] = "Zaktualizowano {0} plik(ów)",
            ["L.Instance.Running"] = "{0} działa",
            ["L.Instance.Stopped"] = "{0} zatrzymane",
            ["L.Library.InstanceRenamed"] = "Nazwa instancji zmieniona",
            ["L.Library.InstanceCreated"] = "Utworzono {0}",
            ["L.Library.InstallingLoader"] = "Instalowanie {0} {1}...",
            ["L.Library.InstanceReady"] = "{0} jest gotowe",
            ["L.Library.MovedToBackups"] = "Przeniesiono {0} do kopii zapasowych",
            ["L.Accounts.ClientIdCleared"] = "Identyfikator klienta usunięty",
            ["L.Accounts.ClientIdSaved"] = "Identyfikator klienta zapisany",
            ["L.Java.NoBuilds"] = "Mojang nie publikuje kompilacji {0} dla tej platformy",
            ["L.Java.Builds"] = "Opublikowane kompilacje ({1}): {0}",
            ["L.Instance.ExitNormal"] = "Zakończono prawidłowo",
            ["L.Instance.ExitCode"] = "Zakończono z kodem {0}",
            ["L.Instance.RunningAs"] = "Działa jako proces {0}",
            ["L.Instance.Healthy"] = "Instalacja jest w porządku",
            ["L.Instance.SkippedProvider"] = "Pominięto {0}: {1}",
            ["L.Instance.ProviderSummary"] = "{0}: aktualizacje: {1}, aktualne: {2}",
            ["L.Instance.NoTrackedContent"] =
                "Ta instancja nie ma jeszcze treści zainstalowanych przez launcher.",
            ["L.Browse.ModpackDownloadFailed"] = "Nie udało się pobrać tego modpacka.",
            ["L.Instance.LaunchFailed"] = "Nie udało się uruchomić tej instancji.",
            ["L.Library.ChooseMinecraftVersion"] = "Wybierz wersję Minecrafta.",
            ["L.Library.ChooseLoaderVersion"] = "Wybierz wersję loadera.",
            ["L.Settings.KeyStoredDegraded"] =
                "Klucz zapisany tylko z uprawnieniami pliku (ta platforma nie ma ochrony systemowej).",
            ["L.Settings.KeyStoredProtected"] =
                "Klucz zapisany i chroniony przez system operacyjny.",
            ["L.Settings.NoKeyStored"] =
                "Brak zapisanego klucza. Przeglądanie CurseForge i instalacja modpacków są wyłączone.",
        };
}
