namespace Ferrite.App.Localization;

/// <summary>Polish interface text. Keys match the English table exactly.</summary>
internal static class StringsPl
{
    internal static IReadOnlyDictionary<string, string> Table { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["L.App.Name"] = "Ferrite",
            ["L.App.Tagline"] = "Launcher Minecrafta",
            ["L.Nav.Library"] = "Biblioteka",
            ["L.Nav.Browse"] = "Przeglądaj",
            ["L.Nav.Java"] = "Java",
            ["L.Nav.Accounts"] = "Konta",
            ["L.Nav.Settings"] = "Ustawienia",
            ["L.Shell.Account"] = "KONTO",
            ["L.Shell.NoAccount"] = "Brak konta",
            ["L.Shell.QuickActions"] = "Szybkie akcje",
            ["L.Shell.QuickActionsPlaceholder"] = "Wpisz polecenie lub nazwę instancji",
            ["L.Quick.GoTo"] = "Przejdź do {0}",
            ["L.Quick.OpenInstance"] = "Otwórz {0}",
            ["L.Quick.LaunchInstance"] = "Uruchom {0}",
            ["L.Quick.NoMatches"] = "Nic nie pasuje.",
            ["L.Common.Ready"] = "Gotowe",
            ["L.Common.Dismiss"] = "Zamknij",
            ["L.Common.Cancel"] = "Anuluj",
            ["L.Common.Refresh"] = "Odśwież",
            ["L.Common.Folder"] = "Folder",
            ["L.Common.OpenFolder"] = "Otwórz folder",
            ["L.Common.Add"] = "Dodaj",
            ["L.Common.Remove"] = "Usuń",
            ["L.Common.Delete"] = "Usuń",
            ["L.Common.OpenFile"] = "Otwórz",
            ["L.Common.Repair"] = "Napraw",
            ["L.Common.Save"] = "Zapisz",
            ["L.Shell.Error"] = "Coś poszło nie tak",
            ["L.Activity.Resolving"] = "Odczytywanie metadanych...",
            ["L.Activity.Planning"] = "Planowanie: {0}...",
            ["L.Activity.Downloading"] = "Pobieranie...",
            ["L.Activity.DownloadingItem"] = "Pobieranie {0} ({1})",
            ["L.Activity.ExtractingNatives"] = "Wypakowywanie bibliotek natywnych ({0})",
            ["L.Activity.Finishing"] = "Kończenie...",

            ["L.Library.SearchInstances"] = "Szukaj instancji",
            ["L.Library.SortRecent"] = "Ostatnio uruchamiane",
            ["L.Library.SortName"] = "Sortuj według nazwy",
            ["L.Library.SortVersion"] = "Sortuj według wersji Minecrafta",
            ["L.Library.SortSize"] = "Sortuj według rozmiaru na dysku",
            ["L.Library.ImportModpack"] = "Importuj modpack",
            ["L.Library.NewInstance"] = "Nowa instancja",
            ["L.Library.Empty"] =
                "Nie ma jeszcze żadnej instancji. Utwórz ją, aby zainstalować Minecrafta, opcjonalnie z mod loaderem.",
            ["L.Library.Play"] = "Graj",
            ["L.Library.Stop"] = "Zatrzymaj",
            ["L.Library.Manage"] = "Zarządzaj",
            ["L.Library.Rename"] = "Zmień nazwę",
            ["L.Library.Clone"] = "Klonuj",
            ["L.Library.RenameTitle"] = "Zmień nazwę instancji",
            ["L.Library.CloneTitle"] = "Klonuj instancję",
            ["L.Library.CloneHint"] =
                "Klon kopiuje mody, konfiguracje i ustawienia tej instancji do niezależnej instancji.",
            ["L.Library.Move"] = "Przenieś",
            ["L.Library.GroupTitle"] = "Przenieś do folderu",
            ["L.Library.GroupHint"] =
                "Foldery porządkują tylko bibliotekę. Wpisz nazwę, aby przypisać instancję, lub wyczyść "
                + "pole, aby usunąć ją z folderu.",
            ["L.Library.GroupAll"] = "Wszystkie foldery",
            ["L.Library.MoveToFolder"] = "Przenieś do folderu",
            ["L.Library.FolderChip"] = "Folder: {0}",
            ["L.Library.CreateTitle"] = "Nowa instancja",
            ["L.Library.FieldName"] = "NAZWA",
            ["L.Library.FieldMinecraftVersion"] = "WERSJA MINECRAFTA",
            ["L.Library.ShowSnapshots"] = "Pokaż snapshoty",
            ["L.Library.FieldLoader"] = "MOD LOADER",
            ["L.Library.FieldLoaderVersion"] = "WERSJA LOADERA",
            ["L.Library.FieldGroup"] = "FOLDER",
            ["L.Library.CreateAndInstall"] = "Utwórz i zainstaluj",

            ["L.Browse.Search"] = "Szukaj",
            ["L.Browse.RefreshInstances"] = "Odśwież instancje",
            ["L.Browse.FieldMinecraftVersion"] = "Wersja Minecrafta",
            ["L.Browse.FieldLoader"] = "Loader",
            ["L.Browse.FieldCategory"] = "Kategoria",
            ["L.Browse.FieldProvider"] = "Źródło",
            ["L.Browse.FieldProjectType"] = "Typ treści",
            ["L.Browse.FieldSort"] = "Kolejność",
            ["L.Browse.AnyCategory"] = "Dowolna kategoria",
            ["L.Browse.AnyVersion"] = "Dowolna wersja",
            ["L.Browse.AnyLoader"] = "Dowolny loader",
            ["L.Browse.About"] = "O TYM PROJEKCIE",
            ["L.Browse.Changelog"] = "ZMIANY",
            ["L.Browse.NoChangelog"] = "Dostawca nie opublikował zmian dla tej wersji.",
            ["L.Browse.Gallery"] = "GALERIA",
            ["L.Browse.BodyTruncated"] = "… opis skrócony; reszta jest na stronie projektu.",
            ["L.Browse.Empty"] =
                "Przeszukaj dostawcę treści w poszukiwaniu modów, modpacków, paczek zasobów i shaderów. "
                + "Wyniki są filtrowane według wersji Minecrafta i loadera wybranej instancji.",
            ["L.Browse.InstallInto"] = "ZAINSTALUJ W",
            ["L.Browse.Saved"] = "Zapisane",
            ["L.Browse.SearchResults"] = "Wyniki wyszukiwania",
            ["L.Browse.Save"] = "Zapisz",
            ["L.Browse.Unsave"] = "Usuń z zapisanych",
            ["L.Browse.SavedProject"] = "Zapisano {0}",
            ["L.Browse.UnsavedProject"] = "Usunięto {0} z zapisanych",
            ["L.Browse.SavedSummary"] = "{0} zapisanych projektów dla tego dostawcy",
            ["L.Browse.NoSaved"] =
                "Nic jeszcze nie zapisano dla tego dostawcy. Wyszukaj, a potem użyj Zapisz na projekcie.",
            ["L.Browse.FieldVersion"] = "WERSJA",
            ["L.Browse.IncludeOptional"] = "Uwzględnij opcjonalne zależności",
            ["L.Browse.OpenProjectPage"] = "Otwórz stronę projektu",
            ["L.Browse.Install"] = "Zainstaluj",
            ["L.Browse.SelectProject"] = "Wybierz projekt, aby zobaczyć jego wersje i zainstalować go.",
            ["L.Browse.SearchPlaceholder"] = "Szukaj w {0}",
            ["L.Browse.Results"] = "Wyniki: {0:N0}",
            ["L.Browse.Installed"] = "Zainstalowano {0} plik(ów) w instancji {1}",
            ["L.Browse.Warnings"] = "Ostrzeżenia: {0}",

            ["L.Accounts.Hint"] =
                "Logowanie korzysta z przepływu device code Microsoftu. Ferrite nigdy nie widzi ani nie zapisuje Twojego hasła.",
            ["L.Accounts.ClientIdPlaceholder"] = "Identyfikator klienta Microsoft (publiczny klient Azure)",
            ["L.Accounts.SaveClientId"] = "Zapisz identyfikator klienta",
            ["L.Accounts.SignIn"] = "Zaloguj się",
            ["L.Accounts.FieldCode"] = "KOD",
            ["L.Accounts.OpenSignInPage"] = "Otwórz stronę logowania",
            ["L.Accounts.Use"] = "Użyj",
            ["L.Accounts.SignOut"] = "Wyloguj się",
            ["L.Accounts.Empty"] =
                "Brak kont. Dodaj identyfikator klienta Microsoft, a następnie zaloguj się.",
            ["L.Accounts.Degraded"] =
                "Ochrona poświadczeń jest ograniczona na tej platformie; tokeny są przechowywane z uprawnieniami tylko dla użytkownika.",

            ["L.Java.Hint"] =
                "Ferrite sprawdza każde środowisko uruchamiając je, więc wymienione są tylko działające instalacje.",
            ["L.Java.Rescan"] = "Skanuj ponownie",
            ["L.Java.UseAsDefault"] = "Ustaw jako domyślne",
            ["L.Java.DownloadHint"] = "POBIERZ ŚRODOWISKO OD MOJANG",
            ["L.Java.ListBuilds"] = "Lista kompilacji",
            ["L.Java.Download"] = "Pobierz",

            ["L.Settings.Appearance"] = "Wygląd",
            ["L.Settings.FieldTheme"] = "MOTYW",
            ["L.Settings.FieldLanguage"] = "JĘZYK",
            ["L.Settings.ShowSnapshots"] = "Pokaż snapshoty na liście wersji",
            ["L.Settings.Network"] = "Sieć",
            ["L.Settings.FieldConcurrentDownloads"] = "RÓWNOLEGŁE POBIERANIA",
            ["L.Settings.FieldProxy"] = "PROXY HTTP",
            ["L.Settings.FieldMirrors"] = "LUSTRA (jedno host=url na linię)",
            ["L.Settings.MirrorsPlaceholder"] = "launchermeta.mojang.com=https://mirror.example/mojang",
            ["L.Settings.MirrorsHint"] =
                "Przekierowuje żądania artefaktów i metadanych dla danego hosta do zaufanego lustra. "
                + "Ścieżka i parametry są zachowane, więc lustro musi mieć identyczny układ.",
            ["L.Settings.Accounts"] = "Konta",
            ["L.Settings.FieldClientId"] = "IDENTYFIKATOR KLIENTA MICROSOFT",
            ["L.Settings.ClientIdHint"] =
                "Wymagany do logowania przez Microsoft. Dokładne kroki opisuje docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Settings.Providers"] = "Dostawcy treści",
            ["L.Settings.FieldCurseForgeKey"] = "KLUCZ API CURSEFORGE",
            ["L.Settings.CurseForgeKeyPlaceholder"] = "Wklej klucz, aby zapisać lub zastąpić obecny",
            ["L.Settings.RemoveKey"] = "Usuń klucz",
            ["L.Settings.CurseForgeHint"] =
                "Przeglądanie CurseForge, instalowanie modów i import modpacków wymagają klucza wydanego "
                + "przez CurseForge. Klucz jest przechowywany poza plikiem ustawień. "
                + "Szczegóły w docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Settings.Storage"] = "Pamięć",
            ["L.Settings.FieldDataRoot"] = "KATALOG DANYCH",
            ["L.Settings.DataRootHint"] =
                "Przeniesienie kopiuje dane launchera i działa od następnego uruchomienia. Zmienna "
                + "środowiskowa FERRITE_HOME nadal ma pierwszeństwo.",
            ["L.Settings.MoveDataFolder"] = "Przenieś katalog danych",
            ["L.Settings.UseDefaultDataFolder"] = "Użyj domyślnej lokalizacji",
            ["L.Settings.DataFolderMoved"] =
                "Skopiowano {0} plik(ów) ({1}) do {2}. Uruchom Ferrite ponownie, aby użyć nowego katalogu.",
            ["L.Settings.DataFolderInvalid"] = "Nie można użyć tego katalogu: {0}",
            ["L.Settings.DataFolderReverted"] =
                "Launcher użyje domyślnej lokalizacji danych przy następnym uruchomieniu.",
            ["L.Settings.DataFolderAlreadyDefault"] =
                "Launcher już używa domyślnej lokalizacji danych.",
            ["L.Settings.FieldCacheSize"] = "ROZMIAR BIBLIOTEKI I PAMIĘCI PODRĘCZNEJ",
            ["L.Settings.OpenDataFolder"] = "Otwórz katalog danych",
            ["L.Settings.OpenLogs"] = "Otwórz logi",
            ["L.Settings.RefreshSize"] = "Odśwież rozmiar",
            ["L.Settings.ClearMetadataCache"] = "Wyczyść pamięć podręczną metadanych",
            ["L.Settings.Updates"] = "Aktualizacje launchera",
            ["L.Settings.FieldUpdateFeed"] = "ADRES KANAŁU AKTUALIZACJI",
            ["L.Settings.CheckOnStartup"] = "Sprawdzaj aktualizacje przy starcie Ferrite",
            ["L.Settings.CheckForUpdates"] = "Sprawdź aktualizacje",
            ["L.Settings.DownloadAndVerify"] = "Pobierz i zweryfikuj",
            ["L.Settings.OpenStaging"] = "Otwórz katalog przygotowania",
            ["L.Settings.HandoffHint"] = "ZAMKNIJ FERRITE, NASTĘPNIE URUCHOM",
            ["L.Settings.FeedHint"] =
                "Kanał musi udostępniać manifest.json podpisany kluczem wbudowanym w tę kopię Ferrite. "
                + "Ferrite nigdy nie zastępuje własnych działających plików; przygotowana wersja jest "
                + "instalowana przez powyższy skrypt, który czeka na zamknięcie Ferrite. "
                + "Szczegóły w docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Settings.Diagnostics"] = "Diagnostyka",
            ["L.Settings.FieldRecentOperations"] = "OSTATNIE OPERACJE",
            ["L.Settings.NoOperations"] = "Nie zapisano jeszcze żadnych operacji.",
            ["L.Settings.FieldBundleNotes"] = "NOTATKI DO PAKIETU POMOCY",
            ["L.Settings.BundleNotesPlaceholder"] = "Co robiłeś, gdy wystąpił problem?",
            ["L.Settings.ExportDiagnostics"] = "Eksportuj pakiet diagnostyczny",
            ["L.Settings.RefreshList"] = "Odśwież listę",
            ["L.Settings.BundleHint"] =
                "Pakiet zawiera logi launchera, tę listę operacji oraz analizę najnowszego raportu awarii. "
                + "Poświadczenia są usuwane przed zapisem.",
            ["L.Settings.SaveSettings"] = "Zapisz ustawienia",
            ["L.Settings.Saved"] = "Ustawienia zapisane",
            ["L.Settings.KeyRemoved"] = "Klucz API CurseForge usunięty",
            ["L.Settings.NoFeed"] = "Nie skonfigurowano kanału aktualizacji.",
            ["L.Settings.CheckFirst"] = "Najpierw sprawdź aktualizacje.",
            ["L.Settings.UpToDate"] = "Ferrite {0} to najnowsze wydanie w tym kanale.",
            ["L.Settings.NoPackage"] =
                "Ferrite {0} jest dostępny, ale kanał nie udostępnia kompilacji dla tej maszyny.",
            ["L.Settings.UpdateAvailable"] = "Ferrite {0} jest dostępny ({1}).",
            ["L.Settings.Staged"] =
                "Ferrite {0} jest przygotowany i zweryfikowany ({1}). Zamknij Ferrite i uruchom poniższe polecenie.",
            ["L.Settings.CacheCleared"] =
                "Pamięć podręczna metadanych wyczyszczona; zostanie pobrana ponownie, gdy będzie potrzebna.",

            ["L.Instance.Back"] = "Wstecz",
            ["L.Instance.Verify"] = "Sprawdź",
            ["L.Instance.ExportPack"] = "Eksportuj paczkę",
            ["L.Instance.UpdateFromPack"] = "Nałóż paczkę na tę instancję",
            ["L.Instance.UpdatedFromPack"] =
                "Nałożono paczkę: pobrano {0} plik(ów), {1} nadpisanie(a).",
            ["L.Instance.TabSettings"] = "Ustawienia",
            ["L.Instance.TabMods"] = "Mody",
            ["L.Instance.TabContent"] = "Treści",
            ["L.Instance.TabWorlds"] = "Światy",
            ["L.Instance.TabServers"] = "Serwery",
            ["L.Instance.TabFiles"] = "Pliki",
            ["L.Instance.TabLogs"] = "Logi",
            ["L.Instance.FieldJavaRuntime"] = "ŚRODOWISKO JAVA",
            ["L.Instance.FieldMaxMemory"] = "MAKS. PAMIĘĆ (MB)",
            ["L.Instance.FieldMinMemory"] = "MIN. PAMIĘĆ (MB)",
            ["L.Instance.FieldWindowSize"] = "ROZMIAR OKNA",
            ["L.Instance.FieldWindowWidth"] = "Szerokość okna",
            ["L.Instance.FieldWindowHeight"] = "Wysokość okna",
            ["L.Common.SelectItem"] = "Zaznacz ten element",
            ["L.Instance.WindowSizeHint"] = "szerokość x wysokość, puste dla domyślnego",
            ["L.Instance.FieldDefaultServer"] = "DOMYŚLNY SERWER (używany przy dołączaniu z biblioteki)",
            ["L.Instance.FieldGroup"] = "FOLDER",
            ["L.Instance.FieldGroupHint"] =
                "Foldery porządkują tylko bibliotekę; nigdy nie zmieniają plików instancji.",
            ["L.Instance.FieldThemeAccent"] = "KOLOR AKCENTU (hex, opcjonalny)",
            ["L.Instance.ThemeHint"] =
                "Akcent barwi baner tej instancji, a obraz tła jest kopiowany do instancji, więc "
                + "przeniesienie oryginału niczego nie zepsuje.",
            ["L.Instance.ThemeAccentInvalid"] =
                "To nie jest kolor. Użyj wartości hex, np. #D08A3E, albo zostaw puste.",
            ["L.Instance.ChooseThemeBackground"] = "Obraz tła",
            ["L.Instance.ClearThemeBackground"] = "Usuń tło",
            ["L.Instance.ThemeBackgroundSet"] = "Zapisano tło dla tej instancji",
            ["L.Instance.ThemeBackgroundCleared"] = "Usunięto tło",
            ["L.Instance.DemoMode"] = "Uruchom w trybie demo",
            ["L.Instance.AcceptEula"] = "Akceptuj EULA Minecrafta dla tej instancji (zapisuje eula.txt)",
            ["L.Instance.AcceptEulaHint"] =
                "Minecraft wymaga tego, aby uruchomić serwer. Akceptacja umowy należy do Ciebie, więc "
                + "Ferrite nigdy nie ustawia jej samodzielnie.",
            ["L.Instance.FieldJvmArguments"] = "DODATKOWE ARGUMENTY JVM (jeden na linię)",
            ["L.Instance.FieldGameArguments"] = "DODATKOWE ARGUMENTY GRY (jeden na linię)",
            ["L.Instance.DropModsHint"] = "Przeciągnij pliki modów tutaj lub użyj opcji Dodaj mody.",
            ["L.Instance.Loader"] = "LOADER",
            ["L.Instance.LoaderVanilla"] = "Vanilla (bez loadera)",
            ["L.Instance.LoaderVersion"] = "WERSJA MOD LOADERA",
            ["L.Instance.LoaderStable"] = "stabilna",
            ["L.Instance.ApplyLoaderVersion"] = "Użyj tej wersji",
            ["L.Instance.NoLoaderToChange"] =
                "Ta instancja działa na czystym Minecrafcie, więc nie ma wersji loadera do zmiany.",
            ["L.Instance.NoLoaderBuilds"] = "Nie opublikowano buildów loadera dla Minecrafta {0}.",
            ["L.Instance.LoaderBuilds"] = "Dostępnych buildów loadera: {0}.",
            ["L.Instance.LoaderAlreadyCurrent"] = "Już działa wersja {0}.",
            ["L.Instance.LoaderSwitched"] = "Ta instancja działa teraz na {0} {1}.",
            ["L.Instance.InstallOptiFine"] = "Zainstaluj OptiFine z pobranego instalatora...",
            ["L.Instance.InstallLabyMod"] = "Zainstaluj LabyMod",
            ["L.Instance.LabyModHint"] =
                "LabyMod publikuje własną kompilację dla każdej wersji Minecrafta; Ferrite ją instaluje i uruchamia.",
            ["L.Instance.LabyModInstalling"] = "Instalowanie LabyMod...",
            ["L.Instance.LabyModInstalled"] = "Zainstalowano LabyMod {0} jako {1}",
            ["L.Instance.OptiFineHint"] =
                "OptiFine nie udostępnia API, więc jego instalator działa na Twoim komputerze i to Ty "
                + "klikasz Zainstaluj w jego oknie. Ferrite uruchamia go z właściwą Javą, a następnie "
                + "przejmuje wynik do własnego magazynu launchera.",
            ["L.Instance.NotAnOptiFineInstaller"] =
                "{0} nie jest instalatorem OptiFine. Pobierz OptiFine_x.y.z_HD_U_x.jar z optifine.net.",
            ["L.Instance.OptiFineVersionMismatch"] =
                "Ten instalator jest dla Minecrafta {0}, a ta instancja używa {1}.",
            ["L.Instance.OptiFineNeedsJava"] =
                "Instalacja OptiFine dla tej wersji wymaga Javy {0}, która nie jest zainstalowana.",
            ["L.Instance.OptiFineRunning"] = "Oczekiwanie na instalator OptiFine ({0})",
            ["L.Instance.OptiFineWaitingForInstaller"] =
                "Dokończ instalację w oknie OptiFine; Ferrite przejmie wynik po jego zamknięciu.",
            ["L.Instance.OptiFineInstallerFailed"] = "Instalator OptiFine zakończył się kodem {0}.",
            ["L.Instance.OptiFineInstalled"] =
                "Zainstalowano {0}; ta instancja uruchamia się teraz z OptiFine.",
            ["L.Instance.OptiFineInstalledWithWarnings"] =
                "Zainstalowano OptiFine z ostrzeżeniami: {0}. Sprawdź log launchera.",
            ["L.Instance.AddMods"] = "Dodaj mody",
            ["L.Instance.Disable"] = "Wyłącz",
            ["L.Instance.Enable"] = "Włącz",
            ["L.Instance.NoMods"] = "W tej instancji nie ma zainstalowanych modów.",
            ["L.Instance.NoModMatches"] = "Żaden zainstalowany mod nie pasuje do wyszukiwania.",
            ["L.Instance.ModSearchPlaceholder"] = "Szukaj modów",
            ["L.Instance.ModLoaderAll"] = "Wszystkie loadery",
            ["L.Instance.ModGroupAll"] = "Wszystkie grupy",
            ["L.Instance.ModGroups"] = "Grupy",
            ["L.Instance.ModGroupHint"] =
                "Grupa to nazwa i reguła: mod trafia do niej, gdy jego nazwa lub nazwa pliku zawiera "
                + "wpisany tekst. Grupy to tylko widok na to, co zainstalowane, więc nie przenoszą plików.",
            ["L.Instance.ModGroupExisting"] = "ISTNIEJĄCA GRUPA",
            ["L.Instance.ModGroupName"] = "NAZWA",
            ["L.Instance.ModGroupMatch"] = "NAZWA LUB NAZWA PLIKU ZAWIERA",
            ["L.Instance.FieldModGroup"] = "GRUPA",
            ["L.Instance.ModGroupNeedsBoth"] = "Grupa wymaga zarówno nazwy, jak i reguły.",
            ["L.Instance.ModGroupSaved"] = "Zapisano grupę {0}",
            ["L.Instance.ModGroupRemoved"] = "Usunięto grupę {0}",
            ["L.Instance.TabAssistant"] = "Asystent",
            ["L.Instance.TabLocalServer"] = "Serwer lokalny",
            ["L.Instance.TabMap"] = "Mapa",
            ["L.Instance.MapWorld"] = "ŚWIAT",
            ["L.Instance.MapCopyTo"] = "KOPIUJ CHUNKI DO",
            ["L.Instance.MapRefresh"] = "Wygeneruj mapę",
            ["L.Instance.MapClearSelection"] = "Wyczyść zaznaczenie",
            ["L.Instance.MapDelete"] = "Usuń zaznaczone chunki",
            ["L.Instance.MapCopy"] = "Kopiuj zaznaczone chunki",
            ["L.Instance.MapSelection"] = "zaznaczono {0} chunków",
            ["L.Instance.MapRendering"] = "Odczytywanie chunków świata...",
            ["L.Instance.MapRendered"] = "Wygenerowano {0} z {1} możliwych chunków.",
            ["L.Instance.MapEmpty"] = "Ten świat nie ma jeszcze chunków na dysku.",
            ["L.Instance.MapNoWorlds"] = "Ta instancja nie ma zapisanych światów.",
            ["L.Instance.MapNoSelection"] = "Najpierw zaznacz chunki na mapie.",
            ["L.Instance.MapCopyTarget"] = "Wybierz inny świat do skopiowania.",
            ["L.Instance.MapDeleting"] = "Usuwanie zaznaczonych chunków...",
            ["L.Instance.MapDeleted"] = "Usunięto {0} chunków; pliki regionów najpierw zarchiwizowano.",
            ["L.Instance.MapCopying"] = "Kopiowanie zaznaczonych chunków...",
            ["L.Instance.MapCopied"] = "Skopiowano {0} chunków do {1}.",
            ["L.Instance.ServerHint"] =
                "Uruchamia własny serwer Minecrafta w wersji tej instancji, w osobnym folderze. "
                + "Poniższe ustawienia należą do launchera; reszta wpisów w server.properties zostaje bez zmian.",
            ["L.Instance.ServerLevelName"] = "NAZWA ŚWIATA",
            ["L.Instance.ServerMotd"] = "WIADOMOŚĆ DNIA",
            ["L.Instance.ServerPort"] = "PORT",
            ["L.Instance.ServerMaxPlayers"] = "MAKS. GRACZY",
            ["L.Instance.ServerMemory"] = "PAMIĘĆ SERWERA",
            ["L.Instance.ServerOnlineMode"] = "Tryb online",
            ["L.Instance.ServerAcceptEula"] = "Akceptuj EULA Minecrafta dla serwera",
            ["L.Instance.ServerPrepare"] = "Przygotuj pliki",
            ["L.Instance.ServerStart"] = "Uruchom serwer",
            ["L.Instance.ServerStop"] = "Zatrzymaj serwer",
            ["L.Instance.ServerExport"] = "Eksportuj serwer",
            ["L.Instance.ServerPreparing"] = "Przygotowywanie serwera lokalnego...",
            ["L.Instance.ServerPrepared"] = "Pliki serwera są gotowe w {0}",
            ["L.Instance.ServerRunning"] = "Serwer działa (pid {0}).",
            ["L.Instance.ServerExited"] = "Serwer zakończył się z kodem {0}.",
            ["L.Instance.ServerStopped"] = "Poproszono serwer o zatrzymanie.",
            ["L.Instance.ServerNoJava"] = "Brak dostępnego środowiska Java dla tej wersji.",
            ["L.Instance.ServerExported"] = "Wyeksportowano serwer do {0}",
            ["L.Instance.RunAssistant"] = "Sprawdź tę instancję",
            ["L.Instance.AssistantHint"] =
                "Czyta logi, raporty awarii, mody i pliki tej instancji.",
            ["L.Instance.AssistantRunning"] = "Sprawdzanie instancji...",
            ["L.Instance.AssistantFoundProblems"] = "Asystent znalazł coś do działania.",
            ["L.Instance.AssistantClean"] = "Asystent nie znalazł nic do działania.",
            ["L.Instance.SortName"] = "Sortuj według nazwy",
            ["L.Instance.SortSize"] = "Sortuj według rozmiaru",
            ["L.Instance.SortLoader"] = "Sortuj według loadera",
            ["L.Instance.ModsShown"] = "Pokazano {0} z {1} modów",
            ["L.Instance.SelectAllMods"] = "Zaznacz wszystkie widoczne",
            ["L.Instance.ClearModSelection"] = "Wyczyść zaznaczenie",
            ["L.Instance.EnableSelected"] = "Włącz zaznaczone",
            ["L.Instance.DisableSelected"] = "Wyłącz zaznaczone",
            ["L.Instance.RemoveSelected"] = "Usuń zaznaczone",
            ["L.Instance.ModsSelected"] = "Zaznaczono {0}",
            ["L.Instance.EnabledMods"] = "Włączono {0} plik(ów) modów.",
            ["L.Instance.DisabledMods"] = "Wyłączono {0} plik(ów) modów.",
            ["L.Instance.RemovedMods"] =
                "Przeniesiono {0} plik(ów) modów z instancji; kopie są w katalogu kopii zapasowych launchera.",
            ["L.Instance.NoModsRemoved"] = "Nie udało się przenieść żadnego pliku moda z instancji.",
            ["L.Instance.ModsFailed"] = "Nie udało się zmienić {0} plik(ów) modów; każdy podaje powód.",
            ["L.Instance.CheckContentUpdates"] = "Sprawdź aktualizacje",
            ["L.Instance.UpdateSelected"] = "Zaktualizuj wybrane",
            ["L.Instance.NoContentUpdates"] =
                "Nie znaleziono aktualizacji. Sprawdzane są tylko treści zainstalowane przez Ferrite; "
                + "modów dodanych samodzielnie launcher nie rusza.",
            ["L.Instance.WorldsHint"] =
                "Kopie zapasowe i usunięte światy trafiają do katalogu kopii launchera.",
            ["L.Instance.OpenSaves"] = "Otwórz zapisy",
            ["L.Instance.Backup"] = "Kopia zapasowa",
            ["L.Instance.PlayWorld"] = "Uruchom ten świat",
            ["L.Instance.Duplicate"] = "Duplikuj",
            ["L.Instance.NoWorlds"] = "Ta instancja nie ma jeszcze zapisanych światów.",
            ["L.Instance.ServerNamePlaceholder"] = "Nazwa (opcjonalna)",
            ["L.Instance.PingAll"] = "Pinguj wszystkie",
            ["L.Instance.SavedServers"] = "ZAPISANE SERWERY",
            ["L.Instance.NoServers"] = "Brak zapisanych serwerów. Dodaj jeden, aby zobaczyć jego status.",
            ["L.Instance.FindLanWorlds"] = "Szukaj światów w sieci lokalnej",
            ["L.Instance.ResourcePacks"] = "PACZKI ZASOBÓW",
            ["L.Instance.ShaderPacks"] = "PACZKI SHADERÓW",
            ["L.Instance.Screenshots"] = "ZDJĘCIA EKRANU",
            ["L.Instance.NoResourcePacks"] = "Brak paczek zasobów.",
            ["L.Instance.NoShaderPacks"] = "Brak paczek shaderów.",
            ["L.Instance.NoScreenshots"] = "Brak zdjęć ekranu.",
            ["L.Instance.Datapacks"] = "DATAPACKI",
            ["L.Instance.NoDatapacks"] = "Ten świat nie ma datapacków.",
            ["L.Instance.NoWorldsForDatapacks"] = "Brak zapisanych światów, więc nie ma datapacków do pokazania.",
            ["L.Instance.CrashReports"] = "RAPORTY AWARII",
            ["L.Instance.NoCrashReports"] = "Brak raportów awarii.",
            ["L.Instance.NoLogs"] = "Brak logów.",
            ["L.Instance.AddServerFirst"] = "Najpierw podaj adres serwera.",
            ["L.Instance.ServerAdded"] = "Serwer dodany",
            ["L.Instance.LanAdded"] = "Dodano do listy serwerów tej instancji",
            ["L.Instance.LanSearching"] =
                "Przeszukiwanie sieci lokalnej. Poproś drugiego gracza o otwarcie świata w sieci LAN.",
            ["L.Instance.LanNone"] = "Nie znaleziono jeszcze światów w sieci LAN.",
            ["L.Instance.LanStopped"] = "Wyszukiwanie w sieci LAN zatrzymane.",
            ["L.Instance.LanUnavailable"] = "Ta maszyna nie może nasłuchiwać światów LAN: {0}",
            ["L.Instance.Verified"] = "Sprawdzono {0} plików ({1})",
            ["L.Instance.CorruptFiles"] = "Brakujące lub uszkodzone pliki: {0}",
            ["L.Instance.Repaired"] = "Instalacja naprawiona",
            ["L.Instance.ProblemsRemain"] = "Pozostało problemów: {0}",
            ["L.Instance.SettingsSaved"] = "Ustawienia zapisane",
            ["L.Instance.Exported"] = "Wyeksportowano {0} plik(ów) do {1}",
            ["L.Instance.AddedMods"] = "Dodano {0} plik(ów) modów",
            ["L.Instance.NoModsAdded"] = "Nie dodano żadnych plików modów",

            ["L.Library.ModpackInstalled"] = "Zainstalowano {0}: {1}",
            ["L.Library.ModpackStatus"] = "{0}: {1} plik(ów), {2} nadpisań",
            ["L.Library.ModpackUnsupported"] =
                "To archiwum nie jest modpackiem: nie zawiera ani modrinth.index.json, ani manifest.json.",
            ["L.Library.UnreadableFile"] = "Nie udało się odczytać tego pliku.",
            ["L.Library.Installing"] = "Instalowanie {0}...",
            ["L.Browse.NoCompatible"] =
                "Żadna wersja {0} nie pasuje do wersji gry ani loadera tej instancji.",
            ["L.Browse.ModpackNoDownload"] = "Tego pliku modpacka nie można pobrać automatycznie.",
            ["L.Browse.Downloading"] = "Pobieranie {0}...",
            ["L.Browse.CacheNote"] =
                "{0} jest nieosiągalny; wyświetlane są wyniki z pamięci podręcznej ({1}).",
            ["L.Java.Found"] = "Znalezione środowiska: {0}",
            ["L.Java.AddPath"] = "Dodaj ścieżkę do Javy",
            ["L.Java.PathRefused"] = "{0} nie odpowiedział jak środowisko Javy.",
            ["L.Java.PathAdded"] = "Dodano {0}.",
            ["L.Java.DefaultNow"] = "Domyślne środowisko to teraz {0}",
            ["L.Java.Provisioned"] = "Zainstalowano {0}",
            ["L.Accounts.NeedClientId"] =
                "Najpierw dodaj identyfikator klienta Microsoft; szczegóły w docs/HUMAN_ACTION_REQUIRED.md.",
            ["L.Accounts.Active"] = "Aktywne konto: {0}",
            ["L.Accounts.SignedOut"] = "Wylogowano",
            ["L.Instance.BackedUp"] = "Kopia zapasowa: {0}",
            ["L.Instance.WorldMoved"] = "Przeniesiono {0} do {1}",
            ["L.Instance.WorldDuplicated"] = "Zduplikowano do {0}",
            ["L.Instance.SelectUpdate"] = "Wybierz co najmniej jedną aktualizację do zastosowania.",
            ["L.Instance.Updated"] = "Zaktualizowano {0} plik(ów)",
            ["L.Instance.Running"] = "{0} działa",
            ["L.Instance.Stopped"] = "{0} zatrzymane",
            ["L.Library.InstanceRenamed"] = "Nazwa instancji zmieniona",
            ["L.Library.InstanceCreated"] = "Utworzono {0}",
            ["L.Library.InstallingLoader"] = "Instalowanie {0} {1}...",
            ["L.Library.InstanceReady"] = "{0} jest gotowe",
            ["L.Library.MovedToBackups"] = "Przeniesiono {0} do kopii zapasowych",
            ["L.Library.Grouped"] = "Przeniesiono {0} do {1}",
            ["L.Library.GroupCleared"] = "Usunięto instancję z folderu",
            ["L.Accounts.ClientIdCleared"] = "Identyfikator klienta usunięty",
            ["L.Accounts.ClientIdSaved"] = "Identyfikator klienta zapisany",
            ["L.Java.NoBuilds"] = "Mojang nie publikuje kompilacji {0} dla tej platformy",
            ["L.Java.Builds"] = "Opublikowane kompilacje ({1}): {0}",
            ["L.Instance.ExitNormal"] = "Zakończono prawidłowo",
            ["L.Instance.ExitCode"] = "Zakończono z kodem {0}",
            ["L.Instance.RunningAs"] = "Działa jako proces {0}",
            ["L.Instance.Healthy"] = "Instalacja jest w porządku",
            ["L.Instance.SkippedProvider"] = "Pominięto {0}: {1}",
            ["L.Instance.ProviderSummary"] = "{0}: aktualizacje: {1}, aktualne: {2}",
            ["L.Instance.NoTrackedContent"] =
                "Ta instancja nie ma jeszcze treści zainstalowanych przez launcher.",
            ["L.Browse.ModpackDownloadFailed"] = "Nie udało się pobrać tego modpacka.",
            ["L.Instance.LaunchFailed"] = "Nie udało się uruchomić tej instancji.",
            ["L.Library.ChooseMinecraftVersion"] = "Wybierz wersję Minecrafta.",
            ["L.Library.ChooseLoaderVersion"] = "Wybierz wersję loadera.",
            ["L.Settings.KeyStoredDegraded"] =
                "Klucz zapisany tylko z uprawnieniami pliku (ta platforma nie ma ochrony systemowej).",
            ["L.Settings.KeyStoredProtected"] =
                "Klucz zapisany i chroniony przez system operacyjny.",
            ["L.Settings.NoKeyStored"] =
                "Brak zapisanego klucza. Przeglądanie CurseForge i instalacja modpacków są wyłączone.",
        };
}
