using System.Text;
using Ferrite.Core.Util;

namespace Ferrite.Core.Update;

/// <summary>
/// Generates the script that applies a staged update. A running executable cannot replace itself on
/// Windows, so the launcher's last act is to write a script and let the user run it: the script
/// waits for this process to exit, copies the staged payload over the install directory, and starts
/// the new build.
/// </summary>
/// <remarks>
/// The script body is a constant. Every value it needs arrives as a named argument, so no
/// path or version from the feed is ever interpolated into script text.
/// </remarks>
public static class UpdateHandoff
{
    public const string ExecutableName = "Ferrite.exe";
    public const string ScriptName = "apply-update.ps1";
    public const string StageMarkerName = ".ferrite-update-stage";

    /// <summary>
    /// PowerShell source. It refuses to touch anything that is not marked as a staging directory, and
    /// it will not delete the staging directory unless the marker file is present.
    /// </summary>
    private const string ScriptBody = """
        # Ferrite update hand-off. Generated by the launcher; safe to delete if unused.
        [CmdletBinding()]
        param(
            [Parameter(Mandatory = $true)][int]$WaitForProcessId,
            [Parameter(Mandatory = $true)][string]$StageDirectory,
            [Parameter(Mandatory = $true)][string]$PayloadDirectory,
            [Parameter(Mandatory = $true)][string]$InstallDirectory,
            [Parameter(Mandatory = $true)][string]$Executable,
            [Parameter(Mandatory = $true)][string]$MarkerName
        )

        $ErrorActionPreference = 'Stop'
        Set-StrictMode -Version Latest

        function Test-MarkedStage {
            param([string]$Path)
            $marker = Join-Path $Path $MarkerName
            return (Test-Path -LiteralPath $marker)
        }

        if (-not (Test-MarkedStage -Path $StageDirectory)) {
            throw "Refusing to run: '$StageDirectory' is not a Ferrite staging directory."
        }

        Write-Output "Waiting for Ferrite (pid $WaitForProcessId) to exit..."
        while (Get-Process -Id $WaitForProcessId -ErrorAction SilentlyContinue) {
            Start-Sleep -Milliseconds 500
        }

        if (-not (Test-Path -LiteralPath (Join-Path $PayloadDirectory $Executable))) {
            throw "The staged payload does not contain $Executable."
        }

        Write-Output "Installing Ferrite into $InstallDirectory..."
        New-Item -ItemType Directory -Path $InstallDirectory -Force | Out-Null
        Copy-Item -Path (Join-Path $PayloadDirectory '*') -Destination $InstallDirectory -Recurse -Force

        $target = Join-Path $InstallDirectory $Executable
        Write-Output "Starting $target"
        Start-Process -FilePath $target

        if (Test-MarkedStage -Path $StageDirectory) {
            Remove-Item -LiteralPath $StageDirectory -Recurse -Force
        }

        Remove-Item -LiteralPath $PSCommandPath -Force -ErrorAction SilentlyContinue
        Write-Output "Ferrite update complete."
        """;

    /// <summary>Writes the hand-off script into a staging directory and returns its path.</summary>
    public static async Task<string> WriteScriptAsync(string directory, CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(directory);
        Directory.CreateDirectory(directory);
        var path = Path.Combine(directory, ScriptName);
        await File.WriteAllTextAsync(path, ScriptBody, new UTF8Encoding(false), cancellationToken)
            .ConfigureAwait(false);
        return path;
    }

    /// <summary>
    /// The command line a user runs to apply the update. Returned as an argument list so nothing is
    /// ever passed through a shell string.
    /// </summary>
    public static IReadOnlyList<string> BuildCommand(
        UpdateStageResult stage,
        int processId,
        string installDirectory)
    {
        ArgumentNullException.ThrowIfNull(stage);
        ArgumentException.ThrowIfNullOrWhiteSpace(installDirectory);

        return
        [
            "-NoProfile",
            "-ExecutionPolicy", "Bypass",
            "-File", stage.ScriptPath,
            "-WaitForProcessId", processId.ToString(System.Globalization.CultureInfo.InvariantCulture),
            "-StageDirectory", stage.StageDirectory,
            "-PayloadDirectory", stage.PayloadDirectory,
            "-InstallDirectory", installDirectory,
            "-Executable", ExecutableName,
            "-MarkerName", StageMarkerName,
        ];
    }

    /// <summary>A single-line form for display, with quoting so paths are unambiguous.</summary>
    public static string BuildCommandLine(UpdateStageResult stage, int processId, string installDirectory)
    {
        var arguments = BuildCommand(stage, processId, installDirectory)
            .Select(argument => argument.Contains(' ', StringComparison.Ordinal) ? $"\"{argument}\"" : argument);
        return "pwsh " + string.Join(' ', arguments);
    }

    /// <summary>True when a directory is one this launcher staged, so cleanup is safe.</summary>
    public static bool IsStagingDirectory(string directory, string markerName = StageMarkerName) =>
        !string.IsNullOrWhiteSpace(directory)
        && File.Exists(Path.Combine(Path.GetFullPath(directory), markerName));
}
